// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mtaschedulermodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import java.util.concurrent.TimeUnit;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Delay extends UserAction<java.lang.Void>
{
	private final java.lang.Long Timeout;

	public Delay(
		IContext context,
		java.lang.Long _timeout
	)
	{
		super(context);
		this.Timeout = _timeout;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
        TimeUnit.MILLISECONDS.sleep(this.Timeout);
        return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Delay";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
