// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mtaschedulermodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import mtaschedulermodule.Misc;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ExecuteInBackground extends UserAction<java.lang.Boolean>
{
	private final java.lang.String microflow;
	private final IMendixObject contextObject;

	public ExecuteInBackground(
		IContext context,
		java.lang.String _microflow,
		IMendixObject _contextObject
	)
	{
		super(context);
		this.microflow = _microflow;
		this.contextObject = _contextObject;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return  Misc.runMicroflowInBackground(getContext(), microflow, contextObject);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExecuteInBackground";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
