// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mtaschedulermodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;
import java.util.ArrayList;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Returns an JSON array string with the split strings.
 */
public class StringSplitter extends UserAction<java.lang.String>
{
	private final java.lang.String InputString;
	private final java.lang.String Delimiter;

	public StringSplitter(
		IContext context,
		java.lang.String _inputString,
		java.lang.String _delimiter
	)
	{
		super(context);
		this.InputString = _inputString;
		this.Delimiter = _delimiter;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        String[] splitStrings = this.InputString.split(this.Delimiter);
        JSONArray jsonArray = new JSONArray();

        for (String string : splitStrings) {
            JSONObject object = new JSONObject();
            object.put("string", string);
            jsonArray.put(object);
        }

        return jsonArray.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringSplitter";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
