// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftp.actions;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.EnumSet;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import net.schmizz.sshj.sftp.OpenMode;
import net.schmizz.sshj.sftp.RemoteFile;
import net.schmizz.sshj.sftp.StatefulSFTPClient;
import net.schmizz.sshj.xfer.InMemoryDestFile;
import sftp.impl.SFTP;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Retrieve a file from the SFTP server and stores it as a Mendix FileDocument.
 */
public class Get extends UserAction<java.lang.Boolean>
{
	private final java.lang.String remoteFile;
	/** @deprecated use targetFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __targetFile;
	private final system.proxies.FileDocument targetFile;

	public Get(
		IContext context,
		java.lang.String _remoteFile,
		IMendixObject _targetFile
	)
	{
		super(context);
		this.remoteFile = _remoteFile;
		this.__targetFile = _targetFile;
		this.targetFile = _targetFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _targetFile);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		StatefulSFTPClient client = SFTP.getClient(getContext());
		RemoteFile handle = client.open(this.remoteFile, EnumSet.of(OpenMode.READ));
		InputStream is = handle.new RemoteFileInputStream() {
			private boolean closed = false;
			@Override
			public synchronized void close() throws IOException {
				if (closed) {
					return;
				}
				try {
					super.close();
				} finally {
					handle.close();
				}
				closed = true;
			}
		};
		
		Core.storeFileDocumentContent(getContext(), targetFile.getMendixObject(), is);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Get";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
