// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftp.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import sftp.impl.SFTP;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ProcessKey extends UserAction<java.lang.Boolean>
{
	/** @deprecated use key.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __key;
	private final sftp.proxies.Key key;

	public ProcessKey(
		IContext context,
		IMendixObject _key
	)
	{
		super(context);
		this.__key = _key;
		this.key = _key == null ? null : sftp.proxies.Key.initialize(getContext(), _key);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		SFTP.validateKey(getContext(), key);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ProcessKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
