// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.Map;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonsqsconnector.impl.AbstractQueueAttributesUsage;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import amazonsqsconnector.proxies.CreateQueueAttributesUsage;
import amazonsqsconnector.proxies.QueueAttributes;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.CreateQueueRequest.Builder;
import software.amazon.awssdk.services.sqs.model.CreateQueueResponse;
import software.amazon.awssdk.services.sqs.model.QueueAttributeName;
import com.mendix.systemwideinterfaces.core.UserAction;

public class CreateQueue extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use CreateQueueRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CreateQueueRequest;
	private final amazonsqsconnector.proxies.CreateQueueRequest CreateQueueRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public CreateQueue(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _createQueueRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__CreateQueueRequest = _createQueueRequest;
		this.CreateQueueRequest = _createQueueRequest == null ? null : amazonsqsconnector.proxies.CreateQueueRequest.initialize(getContext(), _createQueueRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(CreateQueueRequest, "CreateQueueRequest is required");
			requireNonNull(Region, "AWS Region is required");
			validate();
			
			var awsRequest = createRequest();
			
			LOGGER.debug("The following request will be sent to AWS: ", awsRequest);
			
			SqsClient client = AmazonSQSClient.getSQSClient(Credentials, Region, CreateQueueRequest);
			
			var awsResponse = client.createQueue(awsRequest);
			
			LOGGER.debug("The following response was received from AWS: ", awsResponse);
			
			return createQueueResponse(awsResponse).getMendixObject();
			
			
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), ":", e.getStackTrace());
			throw e;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateQueue";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(CreateQueue.class);
	
	private static final int MAX_QUEUE_NAME_LENGHT = 80; // characters
	private QueueAttributes queueAtts;
	
	private void setQueue(QueueAttributes queueAtts) {
		this.queueAtts = queueAtts;
	}
	
		
	private void validate() throws CoreException {
		validateQueueName();
		CreateQueueAttributesUsage queueAttsUsage = CreateQueueRequest.getCreateQueueRequest_CreateQueueAttributesUsage();
		
		if (queueAttsUsage != null) {
			QueueAttributes queueAtts = queueAttsUsage.getAbstractQueueAttributesUsage_QueueAttributes();
			requireNonNull(queueAtts, "A Queue object must be added to the CreateQueueQueueUsage object");
			setQueue(queueAtts);
			AbstractQueueAttributesUsage.validateQueue(queueAttsUsage, CreateQueueRequest.getQueueName(), getContext());
		}
	}
	
	private void validateQueueName() {
		String invalidQueueNameError = "A queue name is required and must be between 1 and " + MAX_QUEUE_NAME_LENGHT + " characters long";
		String queueName = CreateQueueRequest.getQueueName();
		requireNonNull(queueName, invalidQueueNameError);
		if (queueName.isBlank()) {
			throw new IllegalArgumentException(invalidQueueNameError);
		}
		if (queueName.length() > MAX_QUEUE_NAME_LENGHT) {
			throw new IllegalArgumentException(invalidQueueNameError);
		}
	}
	
	private software.amazon.awssdk.services.sqs.model.CreateQueueRequest createRequest() throws CoreException {
		Builder builder = software.amazon.awssdk.services.sqs.model.CreateQueueRequest.builder();
		
		builder.queueName(CreateQueueRequest.getQueueName());
		if (queueAtts != null) {
			Map<QueueAttributeName, String> attributeMap = AbstractQueueAttributesUsage.createQueueAttributeMap(CreateQueueRequest.getCreateQueueRequest_CreateQueueAttributesUsage(), getContext());
			if (!attributeMap.isEmpty()) {
				builder.attributes(attributeMap);
			}
		}
		return builder.build();
	}
	
	private amazonsqsconnector.proxies.CreateQueueResponse createQueueResponse(CreateQueueResponse awsReponse) {
		amazonsqsconnector.proxies.CreateQueueResponse mxResponse = new amazonsqsconnector.proxies.CreateQueueResponse(getContext());
		mxResponse.setQueueURL(awsReponse.queueUrl());
		return mxResponse;
	}
	// END EXTRA CODE
}
