// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import amazonsqsconnector.impl.AbstractBatchResultErrorEntry;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.BatchResultErrorEntry;
import software.amazon.awssdk.services.sqs.model.DeleteMessageBatchRequestEntry;
import software.amazon.awssdk.services.sqs.model.DeleteMessageBatchResponse;
import software.amazon.awssdk.services.sqs.model.DeleteMessageBatchResultEntry;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DeleteMessageBatch extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use DeleteMessageBatchRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeleteMessageBatchRequest;
	private final amazonsqsconnector.proxies.DeleteMessageBatchRequest DeleteMessageBatchRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public DeleteMessageBatch(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _deleteMessageBatchRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__DeleteMessageBatchRequest = _deleteMessageBatchRequest;
		this.DeleteMessageBatchRequest = _deleteMessageBatchRequest == null ? null : amazonsqsconnector.proxies.DeleteMessageBatchRequest.initialize(getContext(), _deleteMessageBatchRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(DeleteMessageBatchRequest, "DeleteMessageBatchRequest is required");
			requireNonNull(Region, "AWS Region is required");
			validateRequest();
		
			var awsRequest = createAWSRequest();
			
			LOGGER.debug("The following request will be sent to AWS: ", awsRequest);
			
			SqsClient client = AmazonSQSClient.getSQSClient(Credentials, Region, DeleteMessageBatchRequest);
		
			var awsResponse = client.deleteMessageBatch(awsRequest);
			
			LOGGER.debug("The following response was received from AWS: ", awsResponse);
			
			return createDeleteMessageBatchResponse(awsResponse).getMendixObject();
			
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), ":", e.getStackTrace());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteMessageBatch";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(DeleteMessageBatch.class);
	
	private static final int MAX_NUMBER_OF_ENTRIES = 10;
	
	private List<amazonsqsconnector.proxies.DeleteMessageBatchRequestEntry> getRequestEntryList() {
		return Core.retrieveByPath(getContext(), DeleteMessageBatchRequest.getMendixObject(), amazonsqsconnector.proxies.DeleteMessageBatchRequestEntry.MemberNames.DeleteMessageBatchRequestEntry_DeleteMessageBatchRequest.toString())
				.stream()				
				.map(mxObject -> amazonsqsconnector.proxies.DeleteMessageBatchRequestEntry.initialize(getContext(), mxObject))
				.collect(Collectors.toList());
	}
	
	private void validateRequest() throws CoreException {
		var queueUrl = DeleteMessageBatchRequest.getQueueUrl();
		requireNonNull(queueUrl, "QueueUrl is required");
		if (queueUrl.isBlank()) {
			throw new IllegalArgumentException("QueueUrl cannot be blank");
		}
		
		var entryList = getRequestEntryList();
		
		if(entryList.isEmpty()) {
			throw new IllegalArgumentException("DeleteMessageBatchRequestEntry is required");
		} 
		
		if(entryList.size() > MAX_NUMBER_OF_ENTRIES) {
			throw new IllegalArgumentException("A maximum number of " + MAX_NUMBER_OF_ENTRIES + " messages can be deleted from a queue");
		} 
			
		entryList.forEach(entry -> validateDeleteMessageBatchRequestEntry(entry));
		
		
	}
	
	private void validateDeleteMessageBatchRequestEntry(amazonsqsconnector.proxies.DeleteMessageBatchRequestEntry entry) {
		requireNonNull(entry.get_id(), "DeleteMessageBatchRequestEntry Id is required");
		if(entry.get_id().isBlank()) {
			throw new IllegalArgumentException("DeleteMessageBatchRequestEntry Id cannot be blank");
		}
		requireNonNull(entry.getReceiptHandle(), "DeleteMessageBatchRequestEntry ReceiptHandle is required");
		if(entry.getReceiptHandle().isBlank()) {
			throw new IllegalArgumentException("DeleteMessageBatchRequestEntry ReceiptHandle cannot be blank");
		}
	}
	
	private software.amazon.awssdk.services.sqs.model.DeleteMessageBatchRequest createAWSRequest() throws CoreException {
		List<amazonsqsconnector.proxies.DeleteMessageBatchRequestEntry> mxEntryList = getRequestEntryList();
		return software.amazon.awssdk.services.sqs.model.DeleteMessageBatchRequest.builder()
				.queueUrl(DeleteMessageBatchRequest.getQueueUrl())
				.entries(createDeleteMessageBatchEntryCollection(mxEntryList))
				.build();
	}
	
	private List<DeleteMessageBatchRequestEntry> createDeleteMessageBatchEntryCollection(List<amazonsqsconnector.proxies.DeleteMessageBatchRequestEntry> mxEntryList){
		List<DeleteMessageBatchRequestEntry> entryCollection = mxEntryList.stream()
			.map(mxEntry -> createDeleteMessageBatchEntry(mxEntry))
			.collect(Collectors.toList());	
		return entryCollection;
	}
	
	private DeleteMessageBatchRequestEntry createDeleteMessageBatchEntry(amazonsqsconnector.proxies.DeleteMessageBatchRequestEntry mxEntry) {
		DeleteMessageBatchRequestEntry awsEntry = DeleteMessageBatchRequestEntry.builder()
				.receiptHandle(mxEntry.getReceiptHandle())
				.id(mxEntry.get_id())
				.build();
		return awsEntry;
	}
	
	private amazonsqsconnector.proxies.DeleteMessageBatchResponse createDeleteMessageBatchResponse(DeleteMessageBatchResponse awsResponse){
		var mxResponse = new amazonsqsconnector.proxies.DeleteMessageBatchResponse(getContext());
		
		awsResponse.successful().forEach(success -> createSuccessResultEntry(success).setDeleteMessageBatchResultEntry_DeleteMessageBatchResponse(mxResponse));
		
		awsResponse.failed().forEach(failure -> createErrorResultEntry(failure).setDeleteMessageBatchResultErrorEntry_DeleteMessageBatchResponse(mxResponse));
		
		return mxResponse;
	}
	
	private amazonsqsconnector.proxies.DeleteMessageBatchResultEntry createSuccessResultEntry(DeleteMessageBatchResultEntry awsEntry) {
		amazonsqsconnector.proxies.DeleteMessageBatchResultEntry mxSuccessResultEntry = new amazonsqsconnector.proxies.DeleteMessageBatchResultEntry(getContext());
		mxSuccessResultEntry.set_id(awsEntry.id());
		return mxSuccessResultEntry;
	}
	
	private amazonsqsconnector.proxies.DeleteMessageBatchResultErrorEntry createErrorResultEntry(BatchResultErrorEntry awsBatchResultErrorEntry){
		amazonsqsconnector.proxies.DeleteMessageBatchResultErrorEntry mxErrorResultEntry = new amazonsqsconnector.proxies.DeleteMessageBatchResultErrorEntry(getContext());
		AbstractBatchResultErrorEntry.setBatchResultErrorEntry(awsBatchResultErrorEntry, mxErrorResultEntry);
		return mxErrorResultEntry;
	}
	// END EXTRA CODE
}
