// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.DeleteQueueRequest;
import software.amazon.awssdk.services.sqs.model.DeleteQueueRequest.Builder;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DeleteQueue extends UserAction<java.lang.Void>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use DeleteQueueRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DeleteQueueRequest;
	private final amazonsqsconnector.proxies.DeleteQueueRequest DeleteQueueRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public DeleteQueue(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _deleteQueueRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__DeleteQueueRequest = _deleteQueueRequest;
		this.DeleteQueueRequest = _deleteQueueRequest == null ? null : amazonsqsconnector.proxies.DeleteQueueRequest.initialize(getContext(), _deleteQueueRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(this.Credentials, "AWS Credentials are required");
			requireNonNull(this.Region, "AWS Region is required");
			requireNonNull(this.DeleteQueueRequest, "DeleteQueueRequest is required");
			
			validateRequest();
			
			SqsClient sqsClient = AmazonSQSClient.getSQSClient(Credentials, Region, DeleteQueueRequest);
			
			DeleteQueueRequest awsRequest = createRequest();
			LOGGER.debug("AWS request: ", awsRequest);
			sqsClient.deleteQueue(awsRequest);
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), ":", e.getStackTrace());
			throw e;
		}
		return null;		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteQueue";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(DeleteQueue.class);
	
	private void validateRequest() {
		requireNonNull(DeleteQueueRequest.getQueueUrl(), "QueueUrl is required");
		if (DeleteQueueRequest.getQueueUrl().isBlank()) {
			throw new IllegalArgumentException("QueueUrl cannot be empty or blank");
		}
	}
	
	private DeleteQueueRequest createRequest() {
		Builder builder = software.amazon.awssdk.services.sqs.model.DeleteQueueRequest.builder();
		builder.queueUrl(this.DeleteQueueRequest.getQueueUrl());
		return builder.build();
	}
	// END EXTRA CODE
}
