// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.List;
import java.util.Map.Entry;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonsqsconnector.impl.AbstractQueueAttributesUsage;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import amazonsqsconnector.proxies.GetQueueAttributesQueueUsage;
import amazonsqsconnector.proxies.RequestedQueueAttribute;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.GetQueueAttributesResponse;
import software.amazon.awssdk.services.sqs.model.QueueAttributeName;
import com.mendix.systemwideinterfaces.core.UserAction;

public class GetQueueAttributes extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use GetQueueAttributesRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __GetQueueAttributesRequest;
	private final amazonsqsconnector.proxies.GetQueueAttributesRequest GetQueueAttributesRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public GetQueueAttributes(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _getQueueAttributesRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__GetQueueAttributesRequest = _getQueueAttributesRequest;
		this.GetQueueAttributesRequest = _getQueueAttributesRequest == null ? null : amazonsqsconnector.proxies.GetQueueAttributesRequest.initialize(getContext(), _getQueueAttributesRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(GetQueueAttributesRequest, "GetQueueAttributesRequest is required");
			requireNonNull(Region, "AWS Region is required");
			
			validate();
			
			var awsRequest = createRequest();
			
			LOGGER.debug("The following request was sent to AWS: ", awsRequest);
			
			SqsClient sqsClient = AmazonSQSClient.getSQSClient(Credentials, Region, GetQueueAttributesRequest);
			
			var awsResponse = sqsClient.getQueueAttributes(awsRequest);
			
			LOGGER.debug("The following response was received from AWS: ", awsResponse);
			
			return createMxResponse(awsResponse).getMendixObject();
			
			
		} catch (Exception e) {
			LOGGER.error("Exception occurred ", e.getMessage());
			throw e;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetQueueAttributes";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(GetQueueAttributes.class);
	
	private void validate() {
		requireNonNull(GetQueueAttributesRequest.getQueueUrl(), "A queue url is required");
		if (GetQueueAttributesRequest.getQueueUrl().isBlank()) {
			throw new IllegalArgumentException("A queue url is required");
		}
	}
	
	private software.amazon.awssdk.services.sqs.model.GetQueueAttributesRequest createRequest() {
		var builder = software.amazon.awssdk.services.sqs.model.GetQueueAttributesRequest.builder();
		
		builder.queueUrl(GetQueueAttributesRequest.getQueueUrl());
		List<QueueAttributeName> attributeNames = getQueueAttributeNames();
		
		if (attributeNames.size() > 0) {
			builder.attributeNames(attributeNames);
		}
		
		return builder.build();
	}
	
	private List<QueueAttributeName> getQueueAttributeNames(){
		return Core.retrieveByPath(getContext(), GetQueueAttributesRequest.getMendixObject(), RequestedQueueAttribute.MemberNames.RequestedQueueAttribute_GetQueueAttributesRequest.toString())
				.stream()
				.map(mxObject -> RequestedQueueAttribute.initialize(getContext(), mxObject))
				.map(requestedAttribute -> QueueAttributeName.valueOf(requestedAttribute.getAttribute().name()))
				.collect(Collectors.toList());
	}
	
	private amazonsqsconnector.proxies.GetQueueAttributesResponse createMxResponse(GetQueueAttributesResponse awsResponse) {
		amazonsqsconnector.proxies.GetQueueAttributesResponse mxResponse = new amazonsqsconnector.proxies.GetQueueAttributesResponse(getContext());
		
		
		// if the attribute map is empty, we don't need to return anything. To make this clear to a user, the response doesn't contain anything
		if (!awsResponse.hasAttributes()) {
			return mxResponse;
		}
		
		var awsAttributeMap = awsResponse.attributes();
				
		GetQueueAttributesQueueUsage queueUsage = new GetQueueAttributesQueueUsage(getContext());
		mxResponse.setGetQueueAttributesResponse_GetQueueAttributesQueueUsage(queueUsage);

		
		awsAttributeMap.entrySet().stream().forEach(attribute -> setGetQueueAttributesQueueUsageValues(queueUsage, attribute));
		
		AbstractQueueAttributesUsage.setAbstractQueueAttribuesUsageValues(queueUsage, awsAttributeMap, GetQueueAttributesRequest.getQueueUrl(), getContext());

		return mxResponse;
	}
	
	// this function only track the attributes that are added to the GetQueueAttributesQueueUsage object. All others are added to the (Fifo)QueueAttributes object
	// and its children.
	// This does mean that the list is looped over twice, but as the list is never more than 20 attributes, this is not an issue with regards to performance. Other 
	// options would have other (bigger) drawbacks than doing it this way. (eg. having to track what was already mapped, or modifying the response received from AWS
	@SuppressWarnings("incomplete-switch")
	private void setGetQueueAttributesQueueUsageValues(GetQueueAttributesQueueUsage queueUsage, Entry<QueueAttributeName, String> attribute) {
		switch (attribute.getKey()) {
		case APPROXIMATE_NUMBER_OF_MESSAGES:
			queueUsage.setApproximateNumberOfMessages(Long.valueOf(attribute.getValue()));
			break;
		case APPROXIMATE_NUMBER_OF_MESSAGES_NOT_VISIBLE:
			queueUsage.setApproximateNumberOfMessagesNotVisible(Long.valueOf(attribute.getValue()));
			break;
		case APPROXIMATE_NUMBER_OF_MESSAGES_DELAYED:
			queueUsage.setApproximateNumberOfMessagesDelayed(Long.valueOf(attribute.getValue()));
		case CREATED_TIMESTAMP:
			queueUsage.setCreatedTimestamp(Long.valueOf(attribute.getValue()));
			break;
		case LAST_MODIFIED_TIMESTAMP:
			queueUsage.setLastModifiedTimestamp(Long.valueOf(attribute.getValue()));
			break;
		case QUEUE_ARN: 
			queueUsage.setQueueARN(attribute.getValue());
			break;
		}
	}
	
	// END EXTRA CODE
}
