// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import amazonsqsconnector.proxies.ListQueue;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.ListQueuesRequest;
import software.amazon.awssdk.services.sqs.model.ListQueuesRequest.Builder;
import software.amazon.awssdk.services.sqs.model.ListQueuesResponse;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ListQueues extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use ListQueuesRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ListQueuesRequest;
	private final amazonsqsconnector.proxies.ListQueuesRequest ListQueuesRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public ListQueues(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _listQueuesRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__ListQueuesRequest = _listQueuesRequest;
		this.ListQueuesRequest = _listQueuesRequest == null ? null : amazonsqsconnector.proxies.ListQueuesRequest.initialize(getContext(), _listQueuesRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(this.Credentials, "AWS Credentials are required");
			requireNonNull(this.Region, "AWS Region is required");
			requireNonNull(this.ListQueuesRequest, "DeleteQueueRequest is required");
			
			validateRequest();
			
			SqsClient sqsClient = AmazonSQSClient.getSQSClient(Credentials, Region, ListQueuesRequest);
			
			var awsRequest = createRequest();
			LOGGER.debug("AWS request: ", awsRequest);
			var awsResponse = sqsClient.listQueues(awsRequest);
			LOGGER.debug("AWS response: ", awsResponse);
			return mapListQueuesResponse(awsResponse).getMendixObject();

		} catch (Exception e) {
			LOGGER.error(e.getMessage(), ":", e.getStackTrace());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListQueues";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ListQueues.class);
	
	private void validateRequest() {
		if (ListQueuesRequest.getMaxResult() <= 0) {
			throw new IllegalArgumentException("Max result must have a positive value");
		}		
	}
	
	private ListQueuesRequest createRequest() {
		Builder builder = software.amazon.awssdk.services.sqs.model.ListQueuesRequest.builder();
		builder.maxResults(ListQueuesRequest.getMaxResult());
		if (ListQueuesRequest.getQueueNamePrefix() != null && !ListQueuesRequest.getQueueNamePrefix().isBlank()) {
			builder.queueNamePrefix(ListQueuesRequest.getQueueNamePrefix().trim());			
		}
		if (ListQueuesRequest.getNextToken() != null && !ListQueuesRequest.getNextToken().isBlank()) {
			builder.nextToken(ListQueuesRequest.getNextToken().trim());
		}
		return builder.build();
	}
	
	private amazonsqsconnector.proxies.ListQueuesResponse mapListQueuesResponse(ListQueuesResponse awsResponse) {
		amazonsqsconnector.proxies.ListQueuesResponse mxListQresponse = new amazonsqsconnector.proxies.ListQueuesResponse(getContext());
		mxListQresponse.setNextToken(awsResponse.nextToken());
		awsResponse.queueUrls().forEach(s -> addQueueToList(s, mxListQresponse) );				
		return mxListQresponse;
	}
	
	private void addQueueToList(String queueUrl, amazonsqsconnector.proxies.ListQueuesResponse mxListQresponse) {
		ListQueue mxQueue = new ListQueue(getContext());
		mxQueue.setQueueUrl(queueUrl);
		mxQueue.setListQueue_ListQueuesResponse(mxListQresponse);		
	}
	// END EXTRA CODE
}
