// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import software.amazon.awssdk.services.sqs.SqsClient;
import com.mendix.systemwideinterfaces.core.UserAction;

public class PurgeQueue extends UserAction<java.lang.Void>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	/** @deprecated use PurgeQueueRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __PurgeQueueRequest;
	private final amazonsqsconnector.proxies.PurgeQueueRequest PurgeQueueRequest;
	private final awsauthentication.proxies.ENUM_Region Region;

	public PurgeQueue(
		IContext context,
		IMendixObject _credentials,
		IMendixObject _purgeQueueRequest,
		java.lang.String _region
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.__PurgeQueueRequest = _purgeQueueRequest;
		this.PurgeQueueRequest = _purgeQueueRequest == null ? null : amazonsqsconnector.proxies.PurgeQueueRequest.initialize(getContext(), _purgeQueueRequest);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(PurgeQueueRequest, "PurgeQueueRequest is required");
			requireNonNull(Region, "AWS Region is required");
			validateRequest();
			
			var awsRequest = createRequest();
			
			LOGGER.debug("The following request will be sent to AWS: ", awsRequest);
			
			SqsClient client = AmazonSQSClient.getSQSClient(Credentials, Region, PurgeQueueRequest);
			
			var awsResponse = client.purgeQueue(awsRequest);
			
			LOGGER.debug("The following response was received from AWS: ", awsResponse);
			
			return null;
			
		} catch (Exception e) {
			LOGGER.error(e.getMessage());
			throw e;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PurgeQueue";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(PurgeQueue.class);
	
	private void validateRequest() {
		var queueUrl = PurgeQueueRequest.getQueueUrl();
		requireNonNull(queueUrl, "QueueUrl is required");
		if (queueUrl.isBlank()) {
			throw new IllegalArgumentException("QueueUrl cannot be blank");
		}
	}
	
	private software.amazon.awssdk.services.sqs.model.PurgeQueueRequest createRequest() throws CoreException {
		return software.amazon.awssdk.services.sqs.model.PurgeQueueRequest.builder()
		.queueUrl(PurgeQueueRequest.getQueueUrl())
		.build();
	}
	// END EXTRA CODE
}
