// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import java.math.BigDecimal;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import amazonsqsconnector.proxies.AbstractMessageAttribute;
import amazonsqsconnector.proxies.BinaryMessageAttribute;
import amazonsqsconnector.proxies.ENUM_ReceiveMessageSystemAttributeNames;
import amazonsqsconnector.proxies.NumberMessageAttribute;
import amazonsqsconnector.proxies.ReceivedMessageAttribute;
import amazonsqsconnector.proxies.ReceivedMessageSystemAttribute;
import amazonsqsconnector.proxies.ReceivedMessage;
import amazonsqsconnector.proxies.RequestedMessageAttribute;
import amazonsqsconnector.proxies.RequestedSystemAttribute;
import amazonsqsconnector.proxies.StringMessageAttribute;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.Message;
import software.amazon.awssdk.services.sqs.model.MessageAttributeValue;
import software.amazon.awssdk.services.sqs.model.QueueAttributeName;
import software.amazon.awssdk.services.sqs.model.ReceiveMessageResponse;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ReceiveMessages extends UserAction<IMendixObject>
{
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	private final awsauthentication.proxies.ENUM_Region Region;
	/** @deprecated use ReceiveMessageRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ReceiveMessageRequest;
	private final amazonsqsconnector.proxies.ReceiveMessageRequest ReceiveMessageRequest;

	public ReceiveMessages(
		IContext context,
		IMendixObject _credentials,
		java.lang.String _region,
		IMendixObject _receiveMessageRequest
	)
	{
		super(context);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
		this.__ReceiveMessageRequest = _receiveMessageRequest;
		this.ReceiveMessageRequest = _receiveMessageRequest == null ? null : amazonsqsconnector.proxies.ReceiveMessageRequest.initialize(getContext(), _receiveMessageRequest);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(ReceiveMessageRequest, "ReceiveMessageRequest is required");
			requireNonNull(Region, "AWS Region is required");
			validateQueueURL();
			
			SqsClient sqsClient = AmazonSQSClient.getSQSClient(Credentials, Region, ReceiveMessageRequest);
			
			software.amazon.awssdk.services.sqs.model.ReceiveMessageRequest awsRequest = getAwsRequest();
			
			LOGGER.debug("AWS Request: ", awsRequest);
			
			ReceiveMessageResponse awsResponse = sqsClient.receiveMessage(awsRequest);
			
			LOGGER.debug("AWS Response: ", awsResponse);
			
			amazonsqsconnector.proxies.ReceiveMessageResponse mxResponse = mapMessagesToMxObjects(awsResponse);
			
			return mxResponse.getMendixObject();
			
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), ":", e.getStackTrace());
			throw e;
		}
		
		
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ReceiveMessages";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(ReceiveMessages.class);
	
	private static final String STRING_DATA_TYPE = "String";
	private static final String NUMBER_DATA_TYPE = "Number";
	private static final String BINARY_DATA_TYPE = "Binary";
	
	
	private void validateQueueURL() {
		String queueURL = ReceiveMessageRequest.getQueueURL();
		requireNonNull(queueURL, "Queue URL is required and cannot be empty");
		if (queueURL.isBlank()) {
			throw new IllegalArgumentException("QueueURL is blank. A valid QueueURL is required");
		}
	}
	
	private List<QueueAttributeName> getSystemAttributeKeys() {
		
		List<QueueAttributeName> systemAttributeKeyList = Core.retrieveByPath(getContext(), ReceiveMessageRequest.getMendixObject(), RequestedSystemAttribute.MemberNames.RequestedSystemAttribute_ReceiveMessageRequest.toString())
				.stream()
				.map(mxObject -> RequestedSystemAttribute.initialize(getContext(), mxObject))
				.map(sysAttribute -> QueueAttributeName.fromValue(sysAttribute.getKey().toString()))
				.collect(Collectors.toList());
		
		return systemAttributeKeyList;
	}
	
	private List<String> getMessageAttributeKeys() {
		
		List<String> messageAttributeKeyList = Core.retrieveByPath(getContext(), ReceiveMessageRequest.getMendixObject(), RequestedMessageAttribute.MemberNames.RequestedMessageAttribute_ReceiveMessageRequest.toString())
				.stream()
				.map(mxObject -> RequestedMessageAttribute.initialize(getContext(), mxObject))
				.map(mesAttribute -> mesAttribute.getKey())
				.collect(Collectors.toList());
		
		return messageAttributeKeyList;
		
	}
	
	private software.amazon.awssdk.services.sqs.model.ReceiveMessageRequest getAwsRequest() {
		List<QueueAttributeName> systemAttributeKeys = getSystemAttributeKeys();
		List<String> messageAttributeKeys = getMessageAttributeKeys();
		var builder = software.amazon.awssdk.services.sqs.model.ReceiveMessageRequest.builder();
		
		builder.queueUrl(ReceiveMessageRequest.getQueueURL());
		
		if (!systemAttributeKeys.isEmpty()) {
			builder.attributeNames(systemAttributeKeys);
		}
		if (!messageAttributeKeys.isEmpty()) {
			builder.messageAttributeNames(messageAttributeKeys);
		}
		if (ReceiveMessageRequest.getMaxNoOfMessages() != null) {
			builder.maxNumberOfMessages(ReceiveMessageRequest.getMaxNoOfMessages());
		}
		if (ReceiveMessageRequest.getWaitTimeSeconds() != null) {
			builder.waitTimeSeconds(ReceiveMessageRequest.getWaitTimeSeconds());
		}
		if (ReceiveMessageRequest.getVisibilityTimeout() != null) {
			builder.visibilityTimeout(ReceiveMessageRequest.getVisibilityTimeout());
		}
		if (ReceiveMessageRequest.getReceiveRequestAttemptId() != null) {
			builder.receiveRequestAttemptId(ReceiveMessageRequest.getReceiveRequestAttemptId());
		}

		return builder.build();
		
	}
	
	private ReceivedMessage createReceivedMessage(Message awsMessage) {
		ReceivedMessage mxReceivedMessage = new ReceivedMessage(getContext());
		
		mxReceivedMessage.setBody(awsMessage.body());
		mxReceivedMessage.setMD5OfBody(awsMessage.md5OfBody());
		mxReceivedMessage.setMD5OfMessageAttributes(awsMessage.md5OfMessageAttributes());
		mxReceivedMessage.setMessageId(awsMessage.messageId());
		mxReceivedMessage.setReceiptHandle(awsMessage.receiptHandle());
		
		mapSystemAttributes(awsMessage, mxReceivedMessage);
		mapMessageAttributes(awsMessage, mxReceivedMessage);
		
		return mxReceivedMessage;
	}
	
	private amazonsqsconnector.proxies.ReceiveMessageResponse mapMessagesToMxObjects(ReceiveMessageResponse awsResponse) {
		
		amazonsqsconnector.proxies.ReceiveMessageResponse mxResponse = new amazonsqsconnector.proxies.ReceiveMessageResponse(getContext());
		List<Message> awsResMessages = awsResponse.messages();
		
		for(Message message : awsResMessages) {
			
			var mxMessage = createReceivedMessage(message);
			mxMessage.setReceivedMessage_ReceiveMessageResponse(mxResponse);
		}
		
		return mxResponse;
	}
	
	private void mapSystemAttributes(Message message, ReceivedMessage mxMessage) {
		for(Entry<String, String> attribute : message.attributesAsStrings().entrySet()) {
			ReceivedMessageSystemAttribute responseAttribute = new ReceivedMessageSystemAttribute(getContext());
			
			responseAttribute.setKey(ENUM_ReceiveMessageSystemAttributeNames.valueOf(attribute.getKey()));
			responseAttribute.setValue(attribute.getValue());
			responseAttribute.setSystemAttribute_ReceivingMessage(mxMessage);
		}
	}
	
	private void mapMessageAttributes(Message message, ReceivedMessage mxMessage) {
		for(Map.Entry<String, MessageAttributeValue> awsMesAttr : message.messageAttributes().entrySet()) {
			AbstractMessageAttribute absMesAttr = createMessageAttribute(awsMesAttr.getValue());
			
			if(absMesAttr != null) {
				absMesAttr.setKey(awsMesAttr.getKey());
				ReceivedMessageAttribute attrUsage = new ReceivedMessageAttribute(getContext());
				
				attrUsage.setAbstractMessageAttributeUsage_AbstractMessageAttribute(absMesAttr);
				attrUsage.setMessageAttribute_ReceivingMessage(mxMessage);
			}
		}
	}
	
	private AbstractMessageAttribute createMessageAttribute(MessageAttributeValue awsValue) {
		switch (awsValue.dataType()) {
		case STRING_DATA_TYPE: {
			StringMessageAttribute stringMesAttr = new StringMessageAttribute(getContext());
			String awsString = awsValue.stringValue();
			stringMesAttr.setValue(awsString);
			return stringMesAttr;
		} case NUMBER_DATA_TYPE: {
			NumberMessageAttribute numberMesAttr = new NumberMessageAttribute(getContext());
			BigDecimal awsNumber = new BigDecimal(awsValue.stringValue());
			numberMesAttr.setValue(awsNumber);
			return numberMesAttr;
		} case BINARY_DATA_TYPE: {
			BinaryMessageAttribute binaryMesAttr = new BinaryMessageAttribute(getContext());
			byte[] bytes = awsValue.binaryValue().asByteArray();
			String base64String = Base64.getEncoder().encodeToString(bytes);
			binaryMesAttr.setBase64EncodedString(base64String);
			return binaryMesAttr;
			
		}
		default:
			LOGGER.error("The Data Type '", awsValue.dataType(), "' of the Message Attribute is currently not supported. Supported Data Types are: String, Number and Binary.");
			return null;
		}
	}
	
	// END EXTRA CODE
}
