// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package amazonsqsconnector.actions;

import static java.util.Objects.requireNonNull;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import amazonsqsconnector.impl.AbstractBatchResultErrorEntry;
import amazonsqsconnector.impl.AmazonSQSClient;
import amazonsqsconnector.impl.MxLogger;
import amazonsqsconnector.proxies.AbstractSendMessageEntry;
import amazonsqsconnector.proxies.BinaryMessageAttribute;
import amazonsqsconnector.proxies.FifoMessage;
import amazonsqsconnector.proxies.NumberMessageAttribute;
import amazonsqsconnector.proxies.SendMessageAttributeUsage;
import amazonsqsconnector.proxies.SendMessageBatchResponse;
import amazonsqsconnector.proxies.SendMessageBatchResultErrorEntry;
import amazonsqsconnector.proxies.SendMessageSystemAttribute;
import amazonsqsconnector.proxies.StandardMessage;
import amazonsqsconnector.proxies.StringMessageAttribute;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.BatchResultErrorEntry;
import software.amazon.awssdk.services.sqs.model.MessageAttributeValue;
import software.amazon.awssdk.services.sqs.model.MessageSystemAttributeNameForSends;
import software.amazon.awssdk.services.sqs.model.MessageSystemAttributeValue;
import software.amazon.awssdk.services.sqs.model.SendMessageBatchRequestEntry;
import software.amazon.awssdk.services.sqs.model.SendMessageBatchResultEntry;
import com.mendix.systemwideinterfaces.core.UserAction;

public class SendMessageBatch extends UserAction<IMendixObject>
{
	/** @deprecated use SendMessageBatchRequest.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __SendMessageBatchRequest;
	private final amazonsqsconnector.proxies.SendMessageBatchRequest SendMessageBatchRequest;
	/** @deprecated use Credentials.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Credentials;
	private final awsauthentication.proxies.Credentials Credentials;
	private final awsauthentication.proxies.ENUM_Region Region;

	public SendMessageBatch(
		IContext context,
		IMendixObject _sendMessageBatchRequest,
		IMendixObject _credentials,
		java.lang.String _region
	)
	{
		super(context);
		this.__SendMessageBatchRequest = _sendMessageBatchRequest;
		this.SendMessageBatchRequest = _sendMessageBatchRequest == null ? null : amazonsqsconnector.proxies.SendMessageBatchRequest.initialize(getContext(), _sendMessageBatchRequest);
		this.__Credentials = _credentials;
		this.Credentials = _credentials == null ? null : awsauthentication.proxies.Credentials.initialize(getContext(), _credentials);
		this.Region = _region == null ? null : awsauthentication.proxies.ENUM_Region.valueOf(_region);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			requireNonNull(Credentials, "AWS Credentials are required");
			requireNonNull(Region, "AWS Region is required");
			requireNonNull(SendMessageBatchRequest, "SendMessageBatchRequest is required");
			validateRequest();
			
			SqsClient sqsClient = AmazonSQSClient.getSQSClient(Credentials, Region, SendMessageBatchRequest);
			
			software.amazon.awssdk.services.sqs.model.SendMessageBatchRequest awsRequest = getAwsRequest();
			
			LOGGER.debug("AWS Request: ", awsRequest);
			
			var awsResponse = sqsClient.sendMessageBatch(awsRequest);
			
			LOGGER.debug("AWS Response: ", awsResponse);
			
			SendMessageBatchResponse mxResponse = mapResponseToMx(awsResponse);
			
			return mxResponse.getMendixObject();
			
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), ":", e.getStackTrace());
			throw e;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SendMessageBatch";
	}

	// BEGIN EXTRA CODE
	private static final MxLogger LOGGER = new MxLogger(SendMessageBatch.class);
	
	private static final int MAX_NUMBER_OF_MESSAGES = 10;
	private static final String STRING_DATA_TYPE = "String";
	private static final String NUMBER_DATA_TYPE = "Number";
	private static final String BINARY_DATA_TYPE = "Binary";
	private static final String FIFO_MESSAGE_TYPE = FifoMessage.entityName;
	private static final String STANDARD_MESSAGE_TYPE = StandardMessage.entityName;
	private static final String STRING_MESSAGE_ATTRIBUTE_TYPE = StringMessageAttribute.entityName;
	private static final String NUMBER_MESSAGE_ATTRIBUTE_TYPE = NumberMessageAttribute.entityName;
	private static final String BINARY_MESSAGE_ATTRIBUTE_TYPE = BinaryMessageAttribute.entityName;
	
	private void validateRequest() throws CoreException {
		String queueURL = SendMessageBatchRequest.getQueueURL();
		
		requireNonNull(queueURL, "Queue URL is required and cannot be empty");
		if (queueURL.isBlank()) {
			throw new IllegalArgumentException("QueueURL is blank. A valid QueueURL is required");
		}
		
		var mxSendMessageList = getSendMessages();
		
		if (mxSendMessageList.isEmpty()) {
			throw new IllegalArgumentException("At least one SendMessageUsage is required");
		}
		
		if (mxSendMessageList.size() > MAX_NUMBER_OF_MESSAGES) {
			throw new IllegalArgumentException("A maximum number of " + MAX_NUMBER_OF_MESSAGES + " messages can be sent per batch");
		}
		
		for(amazonsqsconnector.proxies.SendMessageBatchRequestEntry mxSendMessage : mxSendMessageList) {
			validateSendMessage(mxSendMessage);
		}
	}
	
	private List<amazonsqsconnector.proxies.SendMessageBatchRequestEntry> getSendMessages() {
		return Core.retrieveByPath(getContext(), SendMessageBatchRequest.getMendixObject(), amazonsqsconnector.proxies.SendMessageBatchRequestEntry.MemberNames.SendMessageBatchRequestEntry_SendMessageBatchRequest.toString())
				.stream()
				.map(mxObject -> amazonsqsconnector.proxies.SendMessageBatchRequestEntry.initialize(getContext(), mxObject))
				.collect(Collectors.toList());
	}
	
	private void validateSendMessage(amazonsqsconnector.proxies.SendMessageBatchRequestEntry mxSendMessageEntry) throws CoreException {
		AbstractSendMessageEntry mxAbstractSendMessage = mxSendMessageEntry.getAbstractSendMessageEntry_AbstractSendMessageUsage(getContext());
		
		requireNonNull(mxAbstractSendMessage, "SendMessageUsage is not associated to a specialization of AbstractSendMessage");
		
		validateMessageAttributeUsage(mxAbstractSendMessage);
		
		requireNonNull(mxAbstractSendMessage.get_Id(), "SendMessage ID is required");
		if (mxAbstractSendMessage.get_Id().isBlank()) {
			throw new IllegalArgumentException("SendMessage ID cannot be blank");
		}
		
		requireNonNull(mxAbstractSendMessage.getMessageBody(), "SendMessage MessageBody is required");
		if (mxAbstractSendMessage.getMessageBody().isBlank()) {
			throw new IllegalArgumentException("SendMessage MessageBody cannot be blank");
		}
		
		// Check required attribute of fifo message
		if (mxAbstractSendMessage.getMendixObject().getType().equals(FIFO_MESSAGE_TYPE)) {
			FifoMessage mxFifoMessage = (FifoMessage) mxAbstractSendMessage;
			requireNonNull(mxFifoMessage.getMessageGroupId(), "GroupId of a Fifo Message is required");
			if (mxFifoMessage.getMessageGroupId().isBlank()) {
				throw new IllegalArgumentException("GroupId of a FifoMessage cannot be blank");
			}
		}
	}
	
	private software.amazon.awssdk.services.sqs.model.SendMessageBatchRequest getAwsRequest() throws CoreException {
		List<SendMessageBatchRequestEntry> awsSendMessageBatchRequestEntryList = getEntryList();
		var builder = software.amazon.awssdk.services.sqs.model.SendMessageBatchRequest.builder();
		
		builder
			.queueUrl(SendMessageBatchRequest.getQueueURL())
			.entries(awsSendMessageBatchRequestEntryList);
		
		return builder.build();
		
	}
	
	private List<SendMessageBatchRequestEntry> getEntryList() throws CoreException {
		List<SendMessageBatchRequestEntry> awsSendMessageBatchRequestEntryList = new ArrayList<>();
		var mxSendMessageUsages = getSendMessages();
		
		for(amazonsqsconnector.proxies.SendMessageBatchRequestEntry mxEntry : mxSendMessageUsages) {
			var mxAbstractSendMessage = mxEntry.getAbstractSendMessageEntry_AbstractSendMessageUsage(getContext());
			var mxMessageAttributes = getMessageAttributes(mxAbstractSendMessage);
			var mxSystemAttributes = getSystemAttributes(mxAbstractSendMessage);
			
			var msgBuilder = SendMessageBatchRequestEntry.builder();
			
			msgBuilder
				.id(mxAbstractSendMessage.get_Id())
				.messageBody(mxAbstractSendMessage.getMessageBody());
			
			
			switch (mxAbstractSendMessage.getMendixObject().getType()) {
			case STANDARD_MESSAGE_TYPE: {
				StandardMessage stdMessage = (StandardMessage) mxAbstractSendMessage;
				if (stdMessage.getDelaySeconds() != null) {
					msgBuilder.delaySeconds(stdMessage.getDelaySeconds());
				}
				break;
			}
			case FIFO_MESSAGE_TYPE: {
				FifoMessage fifoMsg = (FifoMessage) mxAbstractSendMessage;
				if (fifoMsg.getMessageDeduplicationId() != null) {
					msgBuilder.messageDeduplicationId(fifoMsg.getMessageDeduplicationId());
				}
				if (fifoMsg.getMessageGroupId() != null) {
					msgBuilder.messageGroupId(fifoMsg.getMessageGroupId());
				}
				break;
			}
			default:
				throw new IllegalArgumentException("Please do not use the AbstractSendMessage Entity. Instead, use one of it's specializations.");
			}
			
			if (!mxMessageAttributes.isEmpty()) {
				msgBuilder.messageAttributes(mxMessageAttributes);
			}
			
			if (!mxSystemAttributes.isEmpty()) {
				msgBuilder.messageSystemAttributes(mxSystemAttributes);
			}
			
			awsSendMessageBatchRequestEntryList.add(msgBuilder.build());
			
		}
		
		return awsSendMessageBatchRequestEntryList;
	}
	
	private Map<String, MessageAttributeValue> getMessageAttributes(AbstractSendMessageEntry mxAbstractSendMessage) throws CoreException {
		Map<String, MessageAttributeValue> awsMessageAttributeMap = new HashMap<>();
		
		var mxSendMessageUsage = Core.retrieveByPath(getContext(), mxAbstractSendMessage.getMendixObject(), SendMessageAttributeUsage.MemberNames.SendMessageAttributeUsage_AbstractSendMessageEntry.toString());
			
		for(var mxObject : mxSendMessageUsage) {
			var absMsgAttr = SendMessageAttributeUsage.initialize(getContext(), mxObject).getAbstractMessageAttributeUsage_AbstractMessageAttribute();
			var msgAttrBuilder = MessageAttributeValue.builder();
			
			switch (absMsgAttr.getMendixObject().getType()) {
			case STRING_MESSAGE_ATTRIBUTE_TYPE: {
				StringMessageAttribute strMsgAttr = (StringMessageAttribute) absMsgAttr;
				msgAttrBuilder
					.dataType(STRING_DATA_TYPE)
					.stringValue(strMsgAttr.getValue());
				
				awsMessageAttributeMap.put(strMsgAttr.getKey(), msgAttrBuilder.build());
				break;
			}
			case NUMBER_MESSAGE_ATTRIBUTE_TYPE: {
				NumberMessageAttribute numMsgAttr = (NumberMessageAttribute) absMsgAttr;
				msgAttrBuilder
					.dataType(NUMBER_DATA_TYPE)
					.stringValue(numMsgAttr.getValue().toString());
				
				awsMessageAttributeMap.put(numMsgAttr.getKey(), msgAttrBuilder.build());
				break;
			}
			case BINARY_MESSAGE_ATTRIBUTE_TYPE: {
				BinaryMessageAttribute binMsgAttr = (BinaryMessageAttribute) absMsgAttr;
				msgAttrBuilder.dataType(BINARY_DATA_TYPE);
				// tested works fine
				byte[] decodedBytes = Base64.getDecoder().decode(binMsgAttr.getBase64EncodedString());
					msgAttrBuilder.binaryValue(SdkBytes.fromByteArray(decodedBytes));
				
					awsMessageAttributeMap.put(binMsgAttr.getKey(), msgAttrBuilder.build());
				break;
			}
			default:
				throw new IllegalArgumentException("Do not use the AbstractMessageAttribute Entity. Instead, use one of it's specializations.");		
			}
		}
			
		return awsMessageAttributeMap;
	}
	
	private void validateMessageAttributeUsage(AbstractSendMessageEntry absSendMessage) throws CoreException {
		Core.retrieveByPath(getContext(), absSendMessage.getMendixObject(), SendMessageAttributeUsage.MemberNames.SendMessageAttributeUsage_AbstractSendMessageEntry.toString())
			.stream()
			.map(mxObject -> SendMessageAttributeUsage.initialize(getContext(), mxObject))
			.forEach(usage -> {
				try {
					var mxMessageAttribute = usage.getAbstractMessageAttributeUsage_AbstractMessageAttribute();
					requireNonNull(mxMessageAttribute, "SendMessageAttributeUsage is not associated to a specialization of AbstractMessageAttribute");
				} catch (CoreException e) {
					LOGGER.error(e.getMessage(), ":", e.getStackTrace());
				}
				
			});
	}
	private Map<MessageSystemAttributeNameForSends, MessageSystemAttributeValue> getSystemAttributes(AbstractSendMessageEntry mxAbstractSendmEssage) {
		
		return Core.retrieveByPath(getContext(), mxAbstractSendmEssage.getMendixObject(), SendMessageSystemAttribute.MemberNames.SendMessageSystemAttribute_AbstractSendMessageEntry.toString())
			.stream()
			.map(mxObject -> SendMessageSystemAttribute.initialize(getContext(), mxObject))
			.map(sysAttr -> getAwsSystemAttributeMapEntry(sysAttr))
			.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
		
	}
	
	private Map.Entry<MessageSystemAttributeNameForSends, MessageSystemAttributeValue> getAwsSystemAttributeMapEntry(SendMessageSystemAttribute mxSystemAttribute) {
		var sysAttrBuilder = MessageSystemAttributeValue.builder();  
		
		sysAttrBuilder
			.dataType(STRING_DATA_TYPE)
			.stringValue(mxSystemAttribute.getValue());
		var awsSysAttr = sysAttrBuilder.build();
		
		return new HashMap.SimpleEntry<>(MessageSystemAttributeNameForSends.valueOf(mxSystemAttribute.getKey().toString()), awsSysAttr);
	}
	
	private SendMessageBatchResponse mapResponseToMx(software.amazon.awssdk.services.sqs.model.SendMessageBatchResponse awsResponse) {
		var mxResponse = new SendMessageBatchResponse(getContext());
		
		awsResponse.successful().forEach(success -> createSendMessageBatchResultEntry(success, mxResponse));
		
		awsResponse.failed().forEach(failure -> createSendMessageBatchResultErrorEntry(failure, mxResponse));
		
		return mxResponse;
	}
	
	private void createSendMessageBatchResultErrorEntry(BatchResultErrorEntry awsError, SendMessageBatchResponse mxResponse) {
		SendMessageBatchResultErrorEntry mxError = new SendMessageBatchResultErrorEntry(getContext());
		AbstractBatchResultErrorEntry.setBatchResultErrorEntry(awsError, mxError);
		mxError.setSendMessageBatchResultErrorEntry_SendMessageBatchResponse(mxResponse);
	}
	
	private void createSendMessageBatchResultEntry(SendMessageBatchResultEntry awsSuccess, SendMessageBatchResponse mxResponse) {
		amazonsqsconnector.proxies.SendMessageBatchResultEntry mxSuccess = new amazonsqsconnector.proxies.SendMessageBatchResultEntry(getContext());
		mapSuccessToMx(awsSuccess, mxSuccess);
		mxSuccess.setSendMessageBatchResultEntry_SendMessageBatchResponse(mxResponse);
	}
	
	private void mapSuccessToMx(SendMessageBatchResultEntry awsSuccess, amazonsqsconnector.proxies.SendMessageBatchResultEntry mxSuccess) {
		mxSuccess.set_Id(awsSuccess.id());
		mxSuccess.setMD5OfMessageAttributes(awsSuccess.md5OfMessageAttributes());
		mxSuccess.setMD5OfMessageBody(awsSuccess.md5OfMessageBody());
		mxSuccess.setMD5OfMessageSystemAttributes(awsSuccess.md5OfMessageSystemAttributes());
		mxSuccess.setMessageId(awsSuccess.messageId());
		mxSuccess.setSequenceNumber(awsSuccess.sequenceNumber());
	}
	
	// END EXTRA CODE
}
