// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mtapluginmodule.proxies;

public enum ConnectionStatus
{
	Connected("49ee75a8-37c5-457c-a73d-ce62bb5a8821"),
	Disconnected("bb8069af-7617-4c33-80ec-49bbdf6c9918"),
	Error("c9b8d81e-dd1d-4e58-bc51-11ec99c0433a"),
	SettingUp("9b35e3b6-87ba-4857-8bc5-6e2276dae606"),
	NotConnected("7954ea09-2f1d-4193-af4c-bb910cddf54d");

	private final java.lang.String i18nCaptionKey;
	
	private ConnectionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("nl_NL", i18nCaptionKey);
	}
}
