// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mtapluginmodule.proxies;

public enum ConnectionStatus
{
	Connected("1837a7ab-f0ce-40f4-a37f-ac6b6f82d730"),
	Disconnected("872c322b-d593-45f9-ba27-72e1611edccb"),
	Error("032b1854-ebd6-4b89-9151-7e84f6bdacad"),
	SettingUp("91f6c448-3a20-4898-9f47-91751a70b9b4"),
	NotConnected("a999cc80-b8a5-492c-b901-ffe554b8e0cd");

	private final java.lang.String i18nCaptionKey;
	
	private ConnectionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("nl_NL", i18nCaptionKey);
	}
}
