// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mtapluginmodule.proxies;

public class MTA_TestRun_Session implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mTA_TestRun_SessionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MtaPluginModule.MTA_TestRun_Session";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MTA_TestRun_Session_Session("MtaPluginModule.MTA_TestRun_Session_Session");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MTA_TestRun_Session(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MTA_TestRun_Session(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mTA_TestRun_SessionMendixObject)
	{
		if (mTA_TestRun_SessionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mTA_TestRun_SessionMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mTA_TestRun_SessionMendixObject = mTA_TestRun_SessionMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mtapluginmodule.proxies.MTA_TestRun_Session initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mtapluginmodule.proxies.MTA_TestRun_Session(context, mendixObject);
	}

	public static mtapluginmodule.proxies.MTA_TestRun_Session load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mtapluginmodule.proxies.MTA_TestRun_Session.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MTA_TestRun_Session_Session
	 */
	public final system.proxies.Session getMTA_TestRun_Session_Session() throws com.mendix.core.CoreException
	{
		return getMTA_TestRun_Session_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of MTA_TestRun_Session_Session
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Session getMTA_TestRun_Session_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MTA_TestRun_Session_Session.toString());
		if (identifier != null) {
			result = system.proxies.Session.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MTA_TestRun_Session_Session
	 * @param mta_testrun_session_session
	 */
	public final void setMTA_TestRun_Session_Session(system.proxies.Session mta_testrun_session_session)
	{
		setMTA_TestRun_Session_Session(getContext(), mta_testrun_session_session);
	}

	/**
	 * Set value of MTA_TestRun_Session_Session
	 * @param context
	 * @param mta_testrun_session_session
	 */
	public final void setMTA_TestRun_Session_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session mta_testrun_session_session)
	{
		if (mta_testrun_session_session == null) {
			getMendixObject().setValue(context, MemberNames.MTA_TestRun_Session_Session.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MTA_TestRun_Session_Session.toString(), mta_testrun_session_session.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mTA_TestRun_SessionMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mtapluginmodule.proxies.MTA_TestRun_Session that = (mtapluginmodule.proxies.MTA_TestRun_Session) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
