// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mtapluginmodule.proxies;

public class TMP_Connection_Status implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tMP_Connection_StatusMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MtaPluginModule.TMP_Connection_Status";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConnectionStatus("ConnectionStatus"),
		ConnectionId("ConnectionId"),
		Reason("Reason");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TMP_Connection_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TMP_Connection_Status(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tMP_Connection_StatusMendixObject)
	{
		if (tMP_Connection_StatusMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!tMP_Connection_StatusMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tMP_Connection_StatusMendixObject = tMP_Connection_StatusMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mtapluginmodule.proxies.TMP_Connection_Status initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mtapluginmodule.proxies.TMP_Connection_Status(context, mendixObject);
	}

	public static mtapluginmodule.proxies.TMP_Connection_Status load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mtapluginmodule.proxies.TMP_Connection_Status.initialize(context, mendixObject);
	}

	/**
	 * Get value of ConnectionStatus
	 * @param connectionstatus
	 */
	public final mtapluginmodule.proxies.ConnectionStatus getConnectionStatus()
	{
		return getConnectionStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionStatus
	 */
	public final mtapluginmodule.proxies.ConnectionStatus getConnectionStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ConnectionStatus.toString());
		if (obj == null) {
			return null;
		}
		return mtapluginmodule.proxies.ConnectionStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ConnectionStatus
	 * @param connectionstatus
	 */
	public final void setConnectionStatus(mtapluginmodule.proxies.ConnectionStatus connectionstatus)
	{
		setConnectionStatus(getContext(), connectionstatus);
	}

	/**
	 * Set value of ConnectionStatus
	 * @param context
	 * @param connectionstatus
	 */
	public final void setConnectionStatus(com.mendix.systemwideinterfaces.core.IContext context, mtapluginmodule.proxies.ConnectionStatus connectionstatus)
	{
		if (connectionstatus != null) {
			getMendixObject().setValue(context, MemberNames.ConnectionStatus.toString(), connectionstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ConnectionStatus.toString(), null);
		}
	}

	/**
	 * @return value of ConnectionId
	 */
	public final java.lang.String getConnectionId()
	{
		return getConnectionId(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionId
	 */
	public final java.lang.String getConnectionId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConnectionId.toString());
	}

	/**
	 * Set value of ConnectionId
	 * @param connectionid
	 */
	public final void setConnectionId(java.lang.String connectionid)
	{
		setConnectionId(getContext(), connectionid);
	}

	/**
	 * Set value of ConnectionId
	 * @param context
	 * @param connectionid
	 */
	public final void setConnectionId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String connectionid)
	{
		getMendixObject().setValue(context, MemberNames.ConnectionId.toString(), connectionid);
	}

	/**
	 * @return value of Reason
	 */
	public final java.lang.String getReason()
	{
		return getReason(getContext());
	}

	/**
	 * @param context
	 * @return value of Reason
	 */
	public final java.lang.String getReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reason.toString());
	}

	/**
	 * Set value of Reason
	 * @param reason
	 */
	public final void setReason(java.lang.String reason)
	{
		setReason(getContext(), reason);
	}

	/**
	 * Set value of Reason
	 * @param context
	 * @param reason
	 */
	public final void setReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reason)
	{
		getMendixObject().setValue(context, MemberNames.Reason.toString(), reason);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tMP_Connection_StatusMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mtapluginmodule.proxies.TMP_Connection_Status that = (mtapluginmodule.proxies.TMP_Connection_Status) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
