// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.common.RoleAssignmentUtil;
import oidc.proxies.Role;
import java.util.List;

public class AzureRoleParse extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String AccessToken;
	/** @deprecated use com.mendix.utils.ListUtils.map(MendixUserRoleList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __MendixUserRoleList;
	private final java.util.List<system.proxies.UserRole> MendixUserRoleList;
	private final java.lang.String ClaimName;

	public AzureRoleParse(
		IContext context,
		java.lang.String _accessToken,
		java.util.List<IMendixObject> _mendixUserRoleList,
		java.lang.String _claimName
	)
	{
		super(context);
		this.AccessToken = _accessToken;
		this.__MendixUserRoleList = _mendixUserRoleList;
		this.MendixUserRoleList = java.util.Optional.ofNullable(_mendixUserRoleList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(mendixUserRoleListElement -> system.proxies.UserRole.initialize(getContext(), mendixUserRoleListElement))
			.collect(java.util.stream.Collectors.toList());
		this.ClaimName = _claimName;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

        final List<Role> idpUserRoles = RoleAssignmentUtil.getIdpRolesFromToken(getContext(), this.AccessToken, this.ClaimName);
        final List<IMendixObject> filteredList = this.MendixUserRoleList.stream().filter(
                mendixUserRole -> idpUserRoles.stream().anyMatch(
                        idpUserRole -> mendixUserRole.getName().equals(idpUserRole.getRoleName()) || mendixUserRole.getModelGUID().equals(idpUserRole.getRoleName())
                )).map(userRole -> {
            Role role = new Role(getContext());
            role.setRoleName(userRole.getModelGUID());
            return role;
        }).map(Role::getMendixObject).toList();
        return filteredList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AzureRoleParse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
