// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.nimbusds.jose.util.JSONObjectUtils;
import usercommons.proxies.UserClaim;
import java.util.ArrayList;
import java.util.Map;

public class CreateClaimsWithJSON extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String OpenIDTokenJSON;

	public CreateClaimsWithJSON(
		IContext context,
		java.lang.String _openIDTokenJSON
	)
	{
		super(context);
		this.OpenIDTokenJSON = _openIDTokenJSON;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        Map<String, Object> jsonObjectMap = JSONObjectUtils.parse(this.OpenIDTokenJSON);

        if (jsonObjectMap == null || jsonObjectMap.isEmpty()) {
            log.info("The provided OpenID Token JSON is empty or null.");
            return new ArrayList<>();
        }

        return jsonObjectMap.entrySet().stream()
                .map(entry -> {
                    UserClaim userClaim = new UserClaim(getContext());
                    userClaim.setName(entry.getKey());

                    Object value = entry.getValue();
                    if (value != null) {
                        userClaim.setValue(String.valueOf(value));
                    }
                    return userClaim.getMendixObject();
                }).toList();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateClaimsWithJSON";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode log = Core.getLogger(CreateClaimsWithJSON.class.getName());
	// END EXTRA CODE
}
