// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.jwk.JWKSet;
import oidc.implementation.MxOIDCHandler;
import oidc.implementation.security.KeyStoreHelper;
import java.util.LinkedList;
import java.util.List;

public class CreatePublicJWKKeySet extends UserAction<java.lang.String>
{
	/** @deprecated use ClientConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfiguration;
	private final oidc.proxies.ClientConfiguration ClientConfiguration;
	/** @deprecated use com.mendix.utils.ListUtils.map(InKeyStores, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __InKeyStores;
	private final java.util.List<oidc.proxies.KeyStore> InKeyStores;

	public CreatePublicJWKKeySet(
		IContext context,
		IMendixObject _clientConfiguration,
		java.util.List<IMendixObject> _inKeyStores
	)
	{
		super(context);
		this.__ClientConfiguration = _clientConfiguration;
		this.ClientConfiguration = _clientConfiguration == null ? null : oidc.proxies.ClientConfiguration.initialize(getContext(), _clientConfiguration);
		this.__InKeyStores = _inKeyStores;
		this.InKeyStores = java.util.Optional.ofNullable(_inKeyStores)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(inKeyStoresElement -> oidc.proxies.KeyStore.initialize(getContext(), inKeyStoresElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<JWK> jwks = new LinkedList<>();
		JWK jwkObj = MxOIDCHandler.getInstance().getJWK(ClientConfiguration,getContext());
		if (jwkObj != null )
			jwks.add(jwkObj);

		if(InKeyStores != null && !InKeyStores.isEmpty()) {
			KeyStoreHelper keyStoreHelper = new KeyStoreHelper(getContext());
			for (oidc.proxies.KeyStore oldKeyStore : InKeyStores) {
				JWK jwk = keyStoreHelper.getJWK(oldKeyStore);
				if (jwk != null)
					jwks.add(jwk);
			}
		}
		JWKSet set = new JWKSet(jwks);
		return set.toPublicJWKSet().toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreatePublicJWKKeySet";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
