// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.common.TokenUtils;
import usercommons.proxies.UserClaim;
import java.util.Map;

public class CreateClaimsWithJSON extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String OpenIDTokenJSON;

	public CreateClaimsWithJSON(
		IContext context,
		java.lang.String _openIDTokenJSON
	)
	{
		super(context);
		this.OpenIDTokenJSON = _openIDTokenJSON;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

        final Map<String, Object> jsonObjectMap = TokenUtils.parseJWTFromString(this.OpenIDTokenJSON).getJWTClaimsSet().getClaims();
        java.util.List<IMendixObject> userClaims = new java.util.ArrayList<>();
        if (jsonObjectMap != null && !jsonObjectMap.isEmpty()) {
            // Extract field names from the JSON object

            // Iterate over the field names and create UserClaim objects
            for (Map.Entry<String, Object> entry : jsonObjectMap.entrySet()) {
                UserClaim userClaim = new UserClaim(getContext()); //Core.instantiate(context, UserClaim.getType());
                userClaim.setName(entry.getKey());

                Object obj = entry.getValue();
                if (obj != null) {
                    String value = String.valueOf(obj);
                    userClaim.setValue(value);
                    userClaims.add(userClaim.getMendixObject());
                }
            }
        } else {
            logNode.info("The provided OpenID Token JSON is empty or null.");
        }
        return userClaims;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateClaimsWithJSON";
	}

	// BEGIN EXTRA CODE
    private static final ILogNode logNode = Core.getLogger("oidc.actions.CreateClaimsWithJSON");
	// END EXTRA CODE
}
