// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.nimbusds.jose.util.JSONObjectUtils;
import com.nimbusds.jwt.JWTClaimsSet;
import oidc.implementation.common.JWTValidator;
import org.apache.commons.lang3.StringUtils;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;

/**
 * Decodes a JWT string into a plain text JSON for the header and payload. This enables the user to implement a specific JSON mapping that decodes the header or payload. Throws an exception when the token could not be decoded or verified.
 */
public class DecodeVerifyJWTPlainText extends UserAction<java.lang.String>
{
	private final java.lang.String encodedJWT;
	private final java.lang.String issuer;
	private final java.lang.String audience;
	private final java.lang.String jwksUri;
	private final java.lang.Long leeway;

	public DecodeVerifyJWTPlainText(
		IContext context,
		java.lang.String _encodedJWT,
		java.lang.String _issuer,
		java.lang.String _audience,
		java.lang.String _jwksUri,
		java.lang.Long _leeway
	)
	{
		super(context);
		this.encodedJWT = _encodedJWT;
		this.issuer = _issuer;
		this.audience = _audience;
		this.jwksUri = _jwksUri;
		this.leeway = _leeway;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        validateInputs();
        int maxClockSkew = 0; // Default value for max clock skew, can be adjusted as needed
        if (this.leeway != null && this.leeway.intValue() > 0) {
            maxClockSkew = this.leeway.intValue(); // Default to 0 if leeway is not provided
        }
        Set<String> audienceSet = StringUtils.isNotBlank(this.audience) ? new HashSet<>(Arrays.asList(this.audience.split(","))) : null;
        final JWTClaimsSet claimsSet = JWTValidator.validate(this.encodedJWT, this.issuer, audienceSet, this.jwksUri, maxClockSkew);
        return JSONObjectUtils.toJSONString(claimsSet.toJSONObject(true));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DecodeVerifyJWTPlainText";
	}

	// BEGIN EXTRA CODE
    void validateInputs() {

        if (this.issuer == null || this.issuer.isEmpty()) {
            throw new IllegalArgumentException("Issuer cannot be empty");
        }
        if (this.jwksUri == null || this.jwksUri.isEmpty()) {
            throw new IllegalArgumentException("JWKS URI cannot be empty");
        }
        if (this.encodedJWT == null || this.encodedJWT.isEmpty()) {
            throw new IllegalArgumentException("Encoded JWT cannot be empty");
        }

    }
	// END EXTRA CODE
}
