// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.common.StaleDBObjectCleaner;
import oidc.proxies.AuthAttempt;
import java.time.Instant;
import java.util.concurrent.TimeUnit;

public class DeleteExpiredAuthAttempts extends UserAction<java.lang.Void>
{
	private final java.lang.Long expiresInMinutes;
	private final java.lang.Long batchSize;

	public DeleteExpiredAuthAttempts(
		IContext context,
		java.lang.Long _expiresInMinutes,
		java.lang.Long _batchSize
	)
	{
		super(context);
		this.expiresInMinutes = _expiresInMinutes;
		this.batchSize = _batchSize;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		long expiredTime = Instant.now().toEpochMilli() - TimeUnit.MINUTES.toMillis(expiresInMinutes);
		StaleDBObjectCleaner.cleanupStaleObjects(AuthAttempt.class, "OIDC.AuthAttempt", "createdDate", expiredTime, batchSize.intValue());

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteExpiredAuthAttempts";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
