// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.jwk.JWK;
import oidc.implementation.MxOIDCHandler;
import oidc.implementation.common.TokenUtils;
import oidc.proxies.Audience;
import java.util.LinkedList;
import java.util.List;

public class GenerateSignedJWTString extends UserAction<java.lang.String>
{
	/** @deprecated use ClientConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfiguration;
	private final oidc.proxies.ClientConfiguration ClientConfiguration;
	/** @deprecated use jwt.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __jwt;
	private final oidc.proxies.JWT jwt;

	public GenerateSignedJWTString(
		IContext context,
		IMendixObject _clientConfiguration,
		IMendixObject _jwt
	)
	{
		super(context);
		this.__ClientConfiguration = _clientConfiguration;
		this.ClientConfiguration = _clientConfiguration == null ? null : oidc.proxies.ClientConfiguration.initialize(getContext(), _clientConfiguration);
		this.__jwt = _jwt;
		this.jwt = _jwt == null ? null : oidc.proxies.JWT.initialize(getContext(), _jwt);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

        final JWK jwkObj = MxOIDCHandler.getInstance().getJWK(ClientConfiguration, getContext());
        final JWSAlgorithm jwsAlgorithm = JWSAlgorithm.parse(ClientConfiguration.getJWT_Sign_Algorithm().name());

        final List<IMendixObject> audiences = Core.retrieveByPath(getContext(),
                jwt.getMendixObject(), oidc.proxies.Audience.MemberNames.Audience_JWT.toString());

        final List<String> auds = new LinkedList<>() {{

            for (IMendixObject audienceObj : audiences) {
                Audience aud = Audience.initialize(getContext(), audienceObj);
                add(aud.getaud());

            }
        }};
        return TokenUtils.createSignedJWTString(jwsAlgorithm, jwkObj, auds, jwt);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateSignedJWTString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
