// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.common.TokenUtils;

public class GetClaimValue extends UserAction<java.lang.String>
{
	private final java.lang.String Token;
	private final java.lang.String ClaimName;

	public GetClaimValue(
		IContext context,
		java.lang.String _token,
		java.lang.String _claimName
	)
	{
		super(context);
		this.Token = _token;
		this.ClaimName = _claimName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return TokenUtils.getClaimValueAsString(this.Token,this.ClaimName);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetClaimValue";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
