// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.nimbusds.jwt.JWT;
import oidc.implementation.common.TokenUtils;

public class GetClientId extends UserAction<java.lang.String>
{
	private final java.lang.String Accesstoken;

	public GetClientId(
		IContext context,
		java.lang.String _accesstoken
	)
	{
		super(context);
		this.Accesstoken = _accesstoken;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final JWT jwt = TokenUtils.parseJWTFromString(this.Accesstoken);
		
		final String sub = jwt.getJWTClaimsSet().getStringClaim("sub");
		final String clientId = jwt.getJWTClaimsSet().getStringClaim("client_id");
		final String appId = jwt.getJWTClaimsSet().getStringClaim("appid");
		final String cid = jwt.getJWTClaimsSet().getStringClaim("cid");
	    if (sub != null && !sub.isEmpty()) {
	        return sub;
	      }else if (clientId != null && !clientId.isEmpty()) {
	        return clientId;
	      }else if (appId != null && !appId.isEmpty()) {
	        return appId;
	      } else if (cid != null && !cid.isEmpty()) {
	        return cid;
	      } else {
	        return null;
	      }
	    
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetClientId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
