// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.core.Core;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.common.Constants;
import oidc.implementation.common.HTTPUtils;
import oidc.implementation.common.URLUtils;
import org.apache.velocity.VelocityContext;
import javax.servlet.http.HttpServletResponse;
import java.io.Writer;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

public class IdPList extends UserAction<java.lang.Void>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(IdPList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __IdPList;
	private final java.util.List<oidc.proxies.ClientConfig> IdPList;
	private final java.lang.String cont;

	public IdPList(
		IContext context,
		java.util.List<IMendixObject> _idPList,
		java.lang.String _cont
	)
	{
		super(context);
		this.__IdPList = _idPList;
		this.IdPList = java.util.Optional.ofNullable(_idPList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(idPListElement -> oidc.proxies.ClientConfig.initialize(getContext(), idPListElement))
			.collect(java.util.stream.Collectors.toList());
		this.cont = _cont;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {

			String baseUrl = Core.getConfiguration().getApplicationRootUrl();
			if (baseUrl == null || baseUrl.isEmpty()) {
				throw new RuntimeException("Application root URL is empty or null. Application root URL must be configured.");
			}
			baseUrl = URLUtils.ensureEndsWithSlash(baseUrl);
			String url = baseUrl + Constants.SSO_PATH + "?";
			if (cont != null) {
				url += Constants.SSO_CONTINUATION_PARAMETER + "=" + URLEncoder.encode(cont, StandardCharsets.UTF_8.toString()) + "&";
			}
			url += Constants.DISCOVERY_ATTRIBUTE + "=";
			VelocityContext ctx = new VelocityContext();
			ctx.put("idpList", IdPList);
			ctx.put("Url", url);
			IMxRuntimeResponse response = getContext().getRuntimeResponse().orElse(null);
			if (response == null) {
				throw new RuntimeException("Failed to retrieve response object.");
			}
			response.setContentType("text/html");
			response.setStatus(HttpServletResponse.SC_OK);
			Writer writer = response.getWriter();
			HTTPUtils.getEngine().mergeTemplate("templates/Login.vm", "UTF-8", ctx, writer);
			writer.flush();
		} catch (Exception e) {
			throw new RuntimeException("Error rendering Velocity template", e);
		}

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IdPList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
