// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.common.RoleAssignmentUtil;
import oidc.proxies.Role;

public class RoleAssignment extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String AccessToken;
	private final java.lang.String ClaimName;

	public RoleAssignment(
		IContext context,
		java.lang.String _accessToken,
		java.lang.String _claimName
	)
	{
		super(context);
		this.AccessToken = _accessToken;
		this.ClaimName = _claimName;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		return RoleAssignmentUtil.getIdpRolesFromToken(getContext(),this.AccessToken,this.ClaimName)
				.stream().map(Role::getMendixObject).toList();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RoleAssignment";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
