// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.implementation.security.KeyStoreHelper;

public class SelfGenKeyStoreFile extends UserAction<java.lang.Void>
{
	/** @deprecated use ClientConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfiguration;
	private final oidc.proxies.ClientConfiguration ClientConfiguration;
	private final oidc.proxies.ENU_SigningAlgorithm SigningAlgorithm;
	private final java.lang.Boolean IsForceReGenerateKeyPair;

	public SelfGenKeyStoreFile(
		IContext context,
		IMendixObject _clientConfiguration,
		java.lang.String _signingAlgorithm,
		java.lang.Boolean _isForceReGenerateKeyPair
	)
	{
		super(context);
		this.__ClientConfiguration = _clientConfiguration;
		this.ClientConfiguration = _clientConfiguration == null ? null : oidc.proxies.ClientConfiguration.initialize(getContext(), _clientConfiguration);
		this.SigningAlgorithm = _signingAlgorithm == null ? null : oidc.proxies.ENU_SigningAlgorithm.valueOf(_signingAlgorithm);
		this.IsForceReGenerateKeyPair = _isForceReGenerateKeyPair;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(this.ClientConfiguration == null){
			//throw new
			return null;
		}
		KeyStoreHelper keyStoreHelper = new KeyStoreHelper(getContext());
		if(ClientConfiguration.getClientConfiguration_KeyStore() == null || this.IsForceReGenerateKeyPair){
			keyStoreHelper.generateSelfKeyPair(this.ClientConfiguration);
		}else if(!ClientConfiguration.getJWT_Sign_Algorithm().equals(SigningAlgorithm)){
			keyStoreHelper.generateSelfKeyPair(this.ClientConfiguration);
		}

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SelfGenKeyStoreFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
