// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import java.util.Optional;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import javax.servlet.http.HttpServletResponse;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import io.netty.handler.codec.http.cookie.CookieHeaderNames;
import static oidc.implementation.CookieUtil.*;

public class SetNonceCookie extends UserAction<java.lang.Void>
{
	private final java.lang.String nonce;

	public SetNonceCookie(
		IContext context,
		java.lang.String _nonce
	)
	{
		super(context);
		this.nonce = _nonce;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Optional<IMxRuntimeRequest> requestOptional = getContext().getRuntimeRequest();
		Optional<IMxRuntimeResponse> responseOptional = getContext().getRuntimeResponse();
		if(requestOptional.isEmpty())
			throw new MendixRuntimeException("RuntimeRequest must not be null");

		if(responseOptional.isEmpty())
			throw new MendixRuntimeException("RuntimeResponse must not be null");

		IMxRuntimeRequest request= requestOptional.get();
		IMxRuntimeResponse response= responseOptional.get();
		HttpServletResponse servletResponse = response.getHttpServletResponse();
		String cookieHeader = createCookie(request, NONCE_COOKIE_NAME, nonce, NONCE_COOKIE_PATH, NONCE_COOKIE_DOMAIN, CookieHeaderNames.SameSite.Lax, 3600);

		servletResponse.addHeader(SET_COOKIE, cookieHeader);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetNonceCookie";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
