// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import oidc.proxies.ENU_SigningAlgorithm;

public class UpdateSigningAlgorithm extends UserAction<java.lang.Void>
{
	private final java.lang.String algorithm;
	/** @deprecated use ClientConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfiguration;
	private final oidc.proxies.ClientConfiguration ClientConfiguration;

	public UpdateSigningAlgorithm(
		IContext context,
		java.lang.String _algorithm,
		IMendixObject _clientConfiguration
	)
	{
		super(context);
		this.algorithm = _algorithm;
		this.__ClientConfiguration = _clientConfiguration;
		this.ClientConfiguration = _clientConfiguration == null ? null : oidc.proxies.ClientConfiguration.initialize(getContext(), _clientConfiguration);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ENU_SigningAlgorithm alg = ENU_SigningAlgorithm.RS256;
		try {
		alg = ENU_SigningAlgorithm.valueOf(algorithm);
	}catch (Exception ex){

		}
		ClientConfiguration.setJWT_Sign_Algorithm(alg);
		return  null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UpdateSigningAlgorithm";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
