// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

public class urlEncode extends UserAction<java.lang.String>
{
	private final java.lang.String cont;

	public urlEncode(
		IContext context,
		java.lang.String _cont
	)
	{
		super(context);
		this.cont = _cont;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			// Encode the input string using UTF-8
			return URLEncoder.encode(cont, StandardCharsets.UTF_8);
		} catch (Exception e) {
			throw new RuntimeException("Error encoding continuation value", e);
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "urlEncode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
