// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mtapluginmodule.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the MtaPluginModule module

	/**
	* A token which identifies an Application Instance created in MTA
	*/
	public static java.lang.String getApplicationInstanceToken()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MtaPluginModule.ApplicationInstanceToken");
	}

	/**
	* An enumeration which determines when to connect to MTA
	* 
	* Possible values:
	* - 'AfterStartup' - When the application is launched automatically connect to MTA
	* - 'Manual'        - When the connect button is pressed on the MTAPluginUser page
	* - 'None'           - Cannot connect to MTA
	*/
	public static java.lang.String getConnectionMethod()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MtaPluginModule.ConnectionMethod");
	}

	/**
	* The password used to logging into MTA as a MTA Connector User
	*/
	public static java.lang.String getMTAConnectionPassword()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MtaPluginModule.MTAConnectionPassword");
	}

	/**
	* Format URL:
	* [wss/ws]://[MTA_DOMAIN]
	* 
	* Example
	* wss://mta.mendixcloud.com
	*/
	public static java.lang.String getMTAConnectionUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MtaPluginModule.MTAConnectionUrl");
	}

	/**
	* The username used to logging into MTA as a MTA Connector User
	*/
	public static java.lang.String getMTAConnectionUsername()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MtaPluginModule.MTAConnectionUsername");
	}
}