// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package usercommons.actions;

import java.util.*;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.ILanguage;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import system.proxies.Language;
import system.proxies.TimeZone;
import system.proxies.User;
import system.proxies.UserReportInfo;
import system.proxies.UserRole;
import system.proxies.UserType;
import usercommons.implementation.common.MendixUtils;
import usercommons.implementation.common.RandomPasswordGenerator;
import usercommons.implementation.exception.UserCommonsException;
import com.mendix.systemwideinterfaces.core.UserAction;
import usercommons.proxies.Claim;
import usercommons.proxies.ClaimEntityAttribute;
import usercommons.proxies.UserClaim;
import usercommons.proxies.UserProvisioning;
import usercommons.proxies.microflows.Microflows;

public class CreateUserRecord extends UserAction<IMendixObject>
{
	/** @deprecated use UserProvisioning.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __UserProvisioning;
	private final usercommons.proxies.UserProvisioning UserProvisioning;
	/** @deprecated use com.mendix.utils.ListUtils.map(Claims, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __Claims;
	private final java.util.List<usercommons.proxies.UserClaim> Claims;
	/** @deprecated use com.mendix.utils.ListUtils.map(ConfigEntityAttributesList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __ConfigEntityAttributesList;
	private final java.util.List<usercommons.proxies.ClaimEntityAttribute> ConfigEntityAttributesList;
	/** @deprecated use UserInfoParameter.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __UserInfoParameter;
	private final usercommons.proxies.UserInfoParam UserInfoParameter;

	public CreateUserRecord(
		IContext context,
		IMendixObject _userProvisioning,
		java.util.List<IMendixObject> _claims,
		java.util.List<IMendixObject> _configEntityAttributesList,
		IMendixObject _userInfoParameter
	)
	{
		super(context);
		this.__UserProvisioning = _userProvisioning;
		this.UserProvisioning = _userProvisioning == null ? null : usercommons.proxies.UserProvisioning.initialize(getContext(), _userProvisioning);
		this.__Claims = _claims;
		this.Claims = java.util.Optional.ofNullable(_claims)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(claimsElement -> usercommons.proxies.UserClaim.initialize(getContext(), claimsElement))
			.collect(java.util.stream.Collectors.toList());
		this.__ConfigEntityAttributesList = _configEntityAttributesList;
		this.ConfigEntityAttributesList = java.util.Optional.ofNullable(_configEntityAttributesList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(configEntityAttributesListElement -> usercommons.proxies.ClaimEntityAttribute.initialize(getContext(), configEntityAttributesListElement))
			.collect(java.util.stream.Collectors.toList());
		this.__UserInfoParameter = _userInfoParameter;
		this.UserInfoParameter = _userInfoParameter == null ? null : usercommons.proxies.UserInfoParam.initialize(getContext(), _userInfoParameter);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
        log.info("Started user creation");
        final String userEntityName = getUserEntityName();
        final String userPrincipalMemberName = getUserPrincipalAttribute();
        final IMendixObject defaultUserRoleObject = getUserRole();

        final ClaimEntityAttribute principalConfigEntityAttribute = getPrincipalConfigEntityAttribute(userPrincipalMemberName);
        final Map<String, UserClaim> claimsMap = getUserClaimMap();

        if (!this.UserProvisioning.getAllowCreateUsers()) {
            log.warn(
                    "User creation is currently disabled due to the inactive status of the 'Allow module to Create users' setting in the Configuration. Please enable this setting to proceed with user creation");
        }

        final String userPrincipalClaimValue = getUserPrincipalClaimValue(principalConfigEntityAttribute, claimsMap);
        final IMendixObject mendixObjectUser = getOrCreateUserMendixObject(userEntityName, userPrincipalMemberName, defaultUserRoleObject, userPrincipalClaimValue);
        updateUserInfo(claimsMap, userPrincipalMemberName, mendixObjectUser);
        setLanguageAndTimeZone(mendixObjectUser);

        try {
            Core.commit(getContext(), mendixObjectUser);
            createOrUpdateUserReportInfo(mendixObjectUser);
            handleCustomProvisioning(mendixObjectUser);
            log.info("User Saved Successfully");

        } catch (RuntimeException e) {
            log.error("An error occured while trying to commit the user entity :" + userPrincipalClaimValue);
            throw new UserCommonsException("An error occured while trying to commit the user entity.", e);
        }

        return mendixObjectUser;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateUserRecord";
	}

	// BEGIN EXTRA CODE

    private final ILogNode log = Core.getLogger("UserCommons");

    private Map<String, UserClaim> getUserClaimMap() {
        Map<String, UserClaim> claimsMap = new HashMap<>();
        this.Claims.forEach(userClaim -> {
            claimsMap.put(userClaim.getName(), userClaim);
        });
        return claimsMap;
    }

    /**
     * Retrieve the entity type for the user
     */
    private String getUserEntityName() throws UserCommonsException {
        String CustomEntity = this.UserProvisioning.getCustomEntity();
        if (CustomEntity != null) {
            return CustomEntity;
        }
        log.error("CustomUserEntity not configured");
        throw new UserCommonsException("CustomUserEntity not configured");
    }

    /**
     * Retrieve the username attribute used for principal name comparison
     */
    private String getUserPrincipalAttribute() throws UserCommonsException {
        String CustomEntityMember = this.UserProvisioning.getCustomEntityMember();
        if (CustomEntityMember != null) {
            return CustomEntityMember;
        }
        log.error("userPrincipleMemberName not configured");
        throw new UserCommonsException("userPrincipleMemberName not configured");
    }

    /**
     * Retrieve the user role to map to the created user
     */
    private IMendixObject getUserRole() throws CoreException {
        UserRole role = this.UserProvisioning.getUserProvisioning_UserRole();
        IMendixObject defaultUserRoleObject = null;
        if (role != null)
            defaultUserRoleObject = role.getMendixObject();
        return defaultUserRoleObject;
    }

    /**
     * Retrieve the configuration entity attribute for the user principal member
     * name
     */
    private ClaimEntityAttribute getPrincipalConfigEntityAttribute(final String userPrincipleMemberName) throws UserCommonsException {
        return ConfigEntityAttributesList.stream()
                .filter(configEntityAttributes -> configEntityAttributes.getEntityMemberName().equals(userPrincipleMemberName))
                .findFirst()
                .orElseThrow(() -> {
                    log.error("Map Principal attribute to any one of attribute of userclaims: " + userPrincipleMemberName);
                    return new UserCommonsException(
                            "Map Principal attribute to any one of attribute of userclaims: " + userPrincipleMemberName);
                });
    }

    /**
     * Retrieve the user principal claim value
     */
    private String getUserPrincipalClaimValue(ClaimEntityAttribute principalConfigEntityAttribute,
                                              Map<String, UserClaim> ClaimsMap) throws UserCommonsException, CoreException {

        final Claim claimEntityAttributeClaim = principalConfigEntityAttribute.getClaimEntityAttribute_Claim();
        if (claimEntityAttributeClaim == null) {
            log.error("Claim Mapping is not found for the configured principal");
            throw new UserCommonsException("Claim Mapping is not found for the configured principal");
        }

        final String userPrincipalClaimName = claimEntityAttributeClaim.getName();
        final UserClaim userClaim = ClaimsMap.get(userPrincipalClaimName);
        if (userClaim != null) {
            UserProvisioning claimEntityAttributeUserProvisioning = principalConfigEntityAttribute.getClaimEntityAttribute_UserProvisioning();
            if (claimEntityAttributeUserProvisioning == null) {
                log.error("No Userprovisioning configuration found for this Attribute Mapping.");
                throw new UserCommonsException("No Userprovisioning configuration found for this Attribute Mapping.");
            }
            // extract the claimValue and substring it if it is greater than the maximum
            // length of the attribute
            final int maxLength = getPrincipalConfigEntityAttributeMaxLength(principalConfigEntityAttribute, claimEntityAttributeUserProvisioning);
            final String claimValue = userClaim.getValue();
            if (maxLength > 0 && claimValue.length() > maxLength) {
                log.warn("Total length of PrincipalClaimValue is" + claimValue.length()
                        + "so truncating the value based on the maximum field length i.e" + maxLength);
                return claimValue.substring(0, maxLength);
            }

            return claimValue;
        }

        log.error("user Principal claim " + userPrincipalClaimName + "value is empty");
        throw new UserCommonsException("user Principal claim " + userPrincipalClaimName
                + "value is empty , Please select the Principal claim which contains value ");

    }

    private static int getPrincipalConfigEntityAttributeMaxLength(ClaimEntityAttribute principalConfigEntityAttribute, UserProvisioning claimEntityAttributeUserProvisioning) {
        final String entityName = claimEntityAttributeUserProvisioning.getCustomEntity();
        final String attributeName = principalConfigEntityAttribute.getEntityMemberName();
        final IMetaObject metaObject = Core.getMetaObject(entityName);
        final IMetaPrimitive metaPrimitive = metaObject.getMetaPrimitive(attributeName);

        return metaPrimitive.getLength();
    }

    /**
     * Finding the user based on the principle name and create if not exists
     */
    private IMendixObject getOrCreateUserMendixObject(String userEntityName, String userPrincipalMemberName,
                                                      IMendixObject defaultUserRoleObject, String UserPrincipalClaimValue) throws UserCommonsException {

        IMendixObject mendixUserObject = getMendixUserObject(userEntityName, userPrincipalMemberName, UserPrincipalClaimValue);
        if (mendixUserObject != null)
            return mendixUserObject;

        if (this.UserProvisioning.getAllowCreateUsers()) {
            mendixUserObject = createUser(userEntityName, userPrincipalMemberName, defaultUserRoleObject,
                    UserPrincipalClaimValue);
        } else {
            String errorMessage = "User lookup of '" + userPrincipalMemberName
                    + "' failed, this user principal does not exist in the Mx database.";
            throw new UserCommonsException(errorMessage);
        }

        return mendixUserObject;
    }

    private IMendixObject getMendixUserObject(String userEntityName, String userPrincipalMemberName, String UserPrincipalClaimValue) throws UserCommonsException {
        List<IMendixObject> mendixUserObjectList = getUserMendixObjects(userEntityName, userPrincipalMemberName, UserPrincipalClaimValue);
        if (mendixUserObjectList.isEmpty()) {
            return null;
        }
        IMendixObject mendixUserObject = mendixUserObjectList.getFirst();
        if (mendixUserObjectList.size() > 1) {
            /*
             * We have multiple users that match the criteria This obviously can't happen
             * for username, but since we facilitate searching on fields such as fullname,
             * email phone, multiple matches are possible.
             */
            User user = evaluateMultipleUserMatches(mendixUserObjectList); // This is a microflow that evaluates and returns a single user.
            if (user == null)
                throw new UserCommonsException("evaluateMultipleUserMatches implementation failed to return User from List of Users ");

            mendixUserObject = user.getMendixObject();
        }
        return mendixUserObject;
    }

    private List<IMendixObject> getUserMendixObjects(String userEntityName, String userPrincipalMemberName, String UserPrincipalClaimValue) {
        List<IMendixObject> mendixUserObjectList = MendixUtils.retrieveFromDatabase(getContext(),
                "//%s[%s=$Username or (%s)=$UsernameSmall]", new HashMap<>() {
                    {
                        put("Username", UserPrincipalClaimValue);
                        put("UsernameSmall", UserPrincipalClaimValue.toLowerCase(Locale.ROOT));
                    }
                }, userEntityName, userPrincipalMemberName, userPrincipalMemberName);
        return mendixUserObjectList;
    }

    private User evaluateMultipleUserMatches(List<IMendixObject> mendixUserObjectList) {
        List<User> userList = new ArrayList<>();
        for (IMendixObject obj : mendixUserObjectList) {
            userList.add(User.initialize(getContext(), obj));
        }

        return Microflows.evaluateMultipleUserMatches(getContext(), userList);
    }

    /**
     * Create User based on Configuration
     */
    private IMendixObject createUser(String userEntityName, String userPrincipleMemberName,
                                     IMendixObject defaultUserRoleObject, String UserPrincipleClaimValue) {
        IMendixObject mxUser;
        mxUser = Core.instantiate(getContext(), userEntityName);
        String userName = UserPrincipleClaimValue.toLowerCase(Locale.ROOT);
        String name = userName.length() > 100 ? userName.substring(0, 100) : userName;
        mxUser.setValue(getContext(), User.MemberNames.Name.toString(), name);
        mxUser.setValue(getContext(), userPrincipleMemberName, userName);
        mxUser.setValue(getContext(), User.MemberNames.Password.toString(),
                RandomPasswordGenerator.generatePswd(15, 20, 4, 4, 4));

        if (defaultUserRoleObject != null) {
            List<IMendixIdentifier> userroles = new ArrayList<IMendixIdentifier>();
            userroles.add(defaultUserRoleObject.getId());
            mxUser.setValue(getContext(), User.MemberNames.UserRoles.toString(), userroles);
            log.info("Associated userrole :"
                    + defaultUserRoleObject.getValue(getContext(), UserRole.MemberNames.Name.toString()));
        }
        return mxUser;
    }

    /**
     * Create the UserReportInfo object when there is no UserReportInfo object with
     * User Update UserType in first UserReportInfo object of list when there is no
     * UserType of UserReportInfo object with User
     *
     * @param mendixUserObject
     * @throws CoreException
     */
    private void createOrUpdateUserReportInfo(IMendixObject mendixUserObject) throws CoreException {
        UserType userType = this.UserProvisioning.getUserType();

        if (userType != null) {
            List<IMendixObject> mendixUserReportInfoList = MendixUtils.retrieveFromDatabase(getContext(), "//%s[%s/%s=%s]",
                    new HashMap<>(), UserReportInfo.entityName,
                    UserReportInfo.MemberNames.UserReportInfo_User, User.entityName, mendixUserObject.getId().toLong());
            if (mendixUserReportInfoList != null && !mendixUserReportInfoList.isEmpty()) {
                boolean userReportInfoNotFound = mendixUserReportInfoList.stream()
                        .noneMatch(mxUserType -> userType.name()
                                .equals(mxUserType.getValue(getContext(), UserReportInfo.MemberNames.UserType.toString()))
                        );
                if (userReportInfoNotFound) {
                    IMendixObject mendixUserReportInfo = mendixUserReportInfoList.getFirst();
                    createUserReportInfoObject(null, mendixUserReportInfo, userType);
                }
            } else {
                IMendixObject mendixUserReportInfoObject = Core.instantiate(getContext(), UserReportInfo.entityName);
                createUserReportInfoObject(mendixUserObject, mendixUserReportInfoObject, userType);
            }
        }
    }

    private void createUserReportInfoObject(IMendixObject mendixUserObject, IMendixObject mendixUserReportInfoObject, UserType userType) throws CoreException {
        UserReportInfo userReportInfo = UserReportInfo.initialize(getContext(), mendixUserReportInfoObject);
        userReportInfo.setUserType(userType);

        if (mendixUserObject != null)
            userReportInfo.setUserReportInfo_User(User.initialize(getContext(), mendixUserObject));
        userReportInfo.commit();
    }

    /**
     * Update User based on Configuration
     */
    private void updateUserInfo(Map<String, UserClaim> ClaimsMap, String userPrincipalMemberName, IMendixObject mendixUserObject) throws UserCommonsException {
        final IMetaObject userEntity = Core.getMetaObject(getUserEntityName());
        for (ClaimEntityAttribute claimEntityAttribute : ConfigEntityAttributesList) {

            try {
                final String entityMemberName = claimEntityAttribute.getEntityMemberName();
                if (claimEntityAttribute.getClaimEntityAttribute_Claim() == null) {
                    String errorMessage = "IdP Attribute is not mapped for the configured entity attribute: "
                            + entityMemberName;
                    log.error(errorMessage);
                    throw new UserCommonsException(errorMessage);
                }

                final IMetaPrimitive mendixObjectMember = userEntity.getMetaPrimitive(entityMemberName);
                final String claimName = claimEntityAttribute.getClaimEntityAttribute_Claim().getName();
                if (ClaimsMap.containsKey(claimName)) {
                    final UserClaim claim = ClaimsMap.get(claimName);
                    // Do not update the user principal value
                    if (userPrincipalMemberName.equals(mendixObjectMember.getName())) {
                        continue;
                    }

                    final Object value = mendixObjectMember.getType() == IMetaPrimitive.PrimitiveType.DateTime
                            ? claim.getDateValue() : claim.getValue();
                    mendixUserObject.setValue(getContext(), mendixObjectMember.getName(), value);

                    log.debug(String.format("%s is updated with  %s in user", claimName, claim.getValue()));
                } else {
                    log.info(String.format("%s claim does not contain a value", claimName));
                }
            } catch (CoreException e) {
                log.error("An error occured while trying to update the user entity with claims",
                        new RuntimeException(e.getCause()));
                throw new UserCommonsException("An error occured while trying to update the user entity with claims");

            }
        }
    }

    /**
     * set Language and TimeZone
     */
    private void setLanguageAndTimeZone(IMendixObject mxUser) throws CoreException {
        String languageValue = UserInfoParameter.getLangCode();
        String timeZoneValue = UserInfoParameter.getTimezoneCode();
        User user = User.initialize(getContext(), mxUser);
        setTimezoneForUser(user, timeZoneValue);
        setLanguageForUser(user, languageValue);
    }

    /**
     * Sets the user's Timezone based on the IdP-provided code. Falls back to the
     * Mendix app default timezone if the IdP code is invalid or missing. Leaves the
     * field empty if no valid timezone is found.
     */
    private void setTimezoneForUser(User user, String timezoneCode) throws CoreException {
        if (timezoneCode != null) {
            List<TimeZone> idPTimezones = TimeZone.load(getContext(), String.format("[Code='%s']", timezoneCode));
            if (idPTimezones != null && !timezoneCode.isEmpty()) {
                user.setUser_TimeZone(idPTimezones.getFirst());
                log.info("Timezone from IdP set successfully to User");
            }
        }
    }

    /**
     * Sets the user's language based on the IdP-provided code. Falls back to the
     * Mendix app default language if the IdP code is invalid or missing. Leaves the
     * field empty if no valid language is found.
     */
    private void setLanguageForUser(User user, String languageCode) throws CoreException {
        if (languageCode != null) {
            List<Language> languages = Language.load(getContext(), String.format("[Code='%s']", languageCode));
            if (languages != null && !languages.isEmpty()) {
                user.setUser_Language(languages.getFirst());
                log.info("Language from IdP set successfully to User");
            }
        }
        if (user.getUser_Language() == null) {
            ILanguage defaultAppLanguage = Core.getLanguage(getContext());
            if (defaultAppLanguage != null) {
                List<Language> defaultLanguage = Language.load(getContext(),
                        String.format("[Code='%s']", defaultAppLanguage.getCode()));
                if (defaultLanguage != null && !defaultLanguage.isEmpty()) {
                    user.setUser_Language(defaultLanguage.getFirst());
                }
            }
        }
    }

    /**
     * Handles custom provisioning logic for a given Mendix user object. If custom
     * user provisioning is defined, executes the associated microflow with the
     * necessary parameters.
     */
    private void handleCustomProvisioning(IMendixObject mendixUserObject) {
        String customUserProvisioning = this.UserProvisioning.getCustomUserProvisioning();
        if (customUserProvisioning != null && !customUserProvisioning.trim().isEmpty()) {
            Core.microflowCall(customUserProvisioning).inTransaction(true)
                    .withParam("UserInfoParameter", UserInfoParameter.getMendixObject())
                    .withParam("User", User.initialize(getContext(), mendixUserObject).getMendixObject())
                    .execute(getContext());
        }
    }
	// END EXTRA CODE
}
