// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package umconnector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Use this action to retrieve a generic entity based on an Mendix identifier and its entity type. This allows us to reuse the Mendix identifier as identifiers without storing it as a second attribute on the entity itself.
 * 
 * This java action does a simple retrieve on the id of the object, if you require a more suffisticated xpath constraint you should still add the extra attribute to the entity. e.g. if you do a retrieve on something based on its id and a isActive boolean.
 */
public class GetMendixObjectByID extends UserAction<IMendixObject>
{
	private final java.lang.Long mxID;
	private final java.lang.String returnType;

	public GetMendixObjectByID(
		IContext context,
		java.lang.Long _mxID,
		java.lang.String _returnType
	)
	{
		super(context);
		this.mxID = _mxID;
		this.returnType = _returnType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return (mxID == null ? null : Core.retrieveId(this.context(), Core.createMendixIdentifier(this.mxID)));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetMendixObjectByID";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
