// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mtapluginmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MtaPluginModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_Setup_Connection_MTABuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MtaPluginModule.ASU_Setup_Connection_MTA");
		return builder;
	}

	public static boolean aSU_Setup_Connection_MTA(IContext context)
	{
		Object result = aSU_Setup_Connection_MTABuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder gET_MtaPluginModule_VersionBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MtaPluginModule.GET_MtaPluginModule_Version");
		return builder;
	}

	public static java.lang.String gET_MtaPluginModule_Version(IContext context)
	{
		Object result = gET_MtaPluginModule_VersionBuilder().execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder setup_ConnectionBuilder(
		mtapluginmodule.proxies.TMP_Connection_Status _tMP_Connection_Status
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MtaPluginModule.Setup_Connection");
		builder = builder.withParam("TMP_Connection_Status", _tMP_Connection_Status);
		return builder;
	}

	public static void setup_Connection(
		IContext context,
		mtapluginmodule.proxies.TMP_Connection_Status _tMP_Connection_Status
	)
	{
		setup_ConnectionBuilder(
				_tMP_Connection_Status
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder update_Connection_StatusBuilder(
		mtapluginmodule.proxies.TMP_Connection_Status _old_Status
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MtaPluginModule.Update_Connection_Status");
		builder = builder.withParam("Old_Status", _old_Status);
		return builder;
	}

	public static void update_Connection_Status(
		IContext context,
		mtapluginmodule.proxies.TMP_Connection_Status _old_Status
	)
	{
		update_Connection_StatusBuilder(
				_old_Status
			)
			.execute(context);
	}
}
